### ISSUE TITLE
Add apply-refact

### ISSUE THREAD

**Issue by alexander-b** [begriffs/haskell-vim-now#102]
Add <https://github.com/mpickering/apply-refact> to let the user automatically apply hlint suggestions.

**Comment by alexander-b** [comment]
vim-plugin: <https://github.com/mpickering/hlint-refactor-vim>.

**Comment by begriffs** [comment]
I love it!

What key combo should we choose to activate the refactoring? The vim plugin [maps](https://github.com/mpickering/hlint-refactor-vim/blob/master/plugin/hlint-refactor.vim#L22-L23) `ta` and `to`. Maybe we want to map `<leader>hL`. That would mirror how `<leader>ht` inspects types and `<leader>hT` inserts a type definition above the current line.

**Comment by SimpleX91** [comment]
Maybe <leader>hr and <leader>hR (refactor) would be better?

**Comment by Tehnix** [comment]
I would actually vote for `<leader>hr` and `<leader>hR` as well, since the refactoring has two modes, current-line and full-file.
