### ISSUE TITLE
Monaco doesn't support powerline by default

### ISSUE THREAD

**Issue by jacksonja** [begriffs/haskell-vim-now#103]
The system installed Monaco on Mac OS X does not support powerline symbols. Custom patched fonts need to be installed. https://github.com/powerline/fonts is a source of precompiled powerline fonts.

**Comment by begriffs** [comment]
Thanks I'll change the info message at the end of installation to point to that link.

Although Monaco by default does not support powerline, the link in the installer points to a patched Monaco. But your link is more flexible because it allows people to choose the font they want.
