### ISSUE TITLE
Split install.sh to use fresh script during update

### ISSUE THREAD

**Issue by SimpleX91** [begriffs/haskell-vim-now#105]
It's not good to store all installation/update steps in single install.sh file. Running install.sh from already installed HVN would result in: 
* unnecessary actions like package installation, stack setup, stack config checks and changes, etc,
* wrong steps being run because of old install.sh script being executed.
Besides, install.sh takes a lot of time, which is not necessary for simple update procedure...

So maybe it's better to split install.sh in (at least) two scripts. Install.sh would just clone (or pull) repo and run setup.sh, for example. And keep install.sh as simple and small as possible.

**Comment by SimpleX91** [comment]
@begriffs Something like this: http://pastebin.com/8Hh5W1hq. Place all common actions there and use them in Setup.sh and Update.sh. Installer would only clone and use one of these.

**Comment by begriffs** [comment]
I like how this looks and would accept a pull request for sure.

**Comment by SimpleX91** [comment]
@begriffs could you please run it on your machine? To make sure colors and detection works. I'm totally new to shell scripting, so need to test everything.
