### ISSUE TITLE
Installing helper binaries fails on mac

### ISSUE THREAD

**Issue by jacksonja** [begriffs/haskell-vim-now#112]
While running the new install script on Mac El Capitan, I get the following error repeated times before the installer completely gives up during the "Installing helper binaries" phase.

/usr/local/bin/ghc-pkg: streamingProcess: runInteractiveProcess: pipe: resource exhausted (Too many open files)
*** Binary installation failed with error 0. Aborting...

**Comment by jacksonja** [comment]
'rm'ing the .cabal, .stack, .ghc, and .local/bin directory resolved the issue. Not sure the cause.

**Comment by begriffs** [comment]
Might be similar to this one: https://github.com/commercialhaskell/stack/issues/1177

Maybe we should add a `ulimit -n 4096` in the install script before doing stack install.

**Comment by begriffs** [comment]
Could you try the installer again? There have been many changes since you opened this issue and I think it will work now.

**Comment by jacksonja** [comment]
I don't remember what the situation was that led to this. However, I did retry the installer and get different errors before I even get to that point. 

Invalid option `--local-bin'

and Invalid option `--stack-root'

**Comment by SX91** [comment]
Update stack

**Comment by jacksonja** [comment]
OK. Everything installs fine now.
