### ISSUE TITLE
Missing symbols for => and /=

### ISSUE THREAD

**Issue by hnykda** [begriffs/haskell-vim-now#117]
Hello,

is there a way how to solve displaying an empty box instead characters `=>` and `/=`? 

Thanks

**Comment by SimpleX91** [comment]
You don't seem to use Utf-8 encoding and font here.

**Comment by hnykda** [comment]
You are right - it's because of `urxvt`, which doesn't show some of the characters properly. Sorry for that, not issue of `hvn`
