### ISSUE TITLE
Haskell linter error message get truncated

### ISSUE THREAD

**Issue by gaoyuan** [begriffs/haskell-vim-now#120]
When I run Haskell linter and move the cursor to the line where there is an error, the status bar at the bottom shows the error message. But since the status bar has only one line, the error message get truncated.

**Comment by begriffs** [comment]
Try running `:Errors` to see the messages in full.

**Comment by gaoyuan** [comment]
Thanks for pointing that out!

**Comment by begriffs** [comment]
It's a standard vim command but maybe it should be documented in this project somewhere. Would you be interested in sending a pull request to update the readme?
