### ISSUE TITLE
Include ObviousResize plugin by default

### ISSUE THREAD

**Issue by Tehnix** [begriffs/haskell-vim-now#124]
I often find myself resizing splits, and absolutely love the [talek/obvious-resize](https://github.com/talek/obvious-resize) plugin for this.

I was wondering if this is something we'd wanna include in HVN by default, or just keep it minimal and let the user add it themselves?

As a side note: I typically bind this to shift-[hjkl] to resize, which goes nicely with ctrl-[hjkl] to move around.

**Comment by begriffs** [comment]
There are plenty of non-minimal things in the config already so I'm open to adding it. The tricky part is what keys to bind it to. Shift-J is already taken for joining two lines together and I use it all the time.

Alternatively it is possible to customize your installation
https://github.com/begriffs/haskell-vim-now#customizing

**Comment by begriffs** [comment]
Actually on second thought these capital letter bindings are already taken in standard vim and are very common (I use J every day). I'd say let's leave this as an optional customization rather than baking it in.
