### ISSUE TITLE
configuring the use of powerline symbols

### ISSUE THREAD

**Issue by azadbolour** [begriffs/haskell-vim-now#126]
After a successful installation on MAC OSX the setup program prints:

Configure your terminal to use a font with Powerline symbols.
https://powerline.readthedocs.org/en/master/installation/osx.html#fonts-installation

But after reading the indicated section of the documentation, I remained confused about where the fonts come from. It might be helpful for some uninitiated with Powerline like myself to provide more information about the specific steps needed to get the fonts, locate them, and configure them.

Thanks.

Azad

**Comment by begriffs** [comment]
Should I have it use this link instead? Is it more helpful?

https://powerline.readthedocs.org/en/master/installation.html#fonts-installation

**Comment by azadbolour** [comment]
Yes this is probably closer. But I still had to fill in some gaps. First, I did not know which font(s) I should install. So I figured install them all. I followed the link to the github for the fonts, cloned the repository and used their install.sh script (as per their README) to install the fonts. But then there were also font installation instructions on the fonts-installation page itself. These are in the section originally printed out by the haskell-vim-now installer. I assumed these were now redundant.

**Comment by begriffs** [comment]
Were you able to get the powerline fonts working with the new instructions despite some redundancy in the docs?

**Comment by azadbolour** [comment]
I was able to install the fonts, and according to the documentation, I did
not have to do anything else for my setup using MAC and generic vim. But I
am not sure how to tell that vim is actually using them. What is an easy
vim interaction that would show that the fonts have been made available to
vim?

Thanks.

Azad
