### ISSUE TITLE
multiline comment syntax highlighting

### ISSUE THREAD

**Issue by akhileshs** [begriffs/haskell-vim-now#129]
![1](https://cloud.githubusercontent.com/assets/7877428/11912186/0855a288-a658-11e5-97cc-c331244339b6.png)

I noticed that multi-line comments don't get syntax highlighting as shown above. Any help would be appreciated!

Thanks,
Akhilesh Srikanth

**Comment by begriffs** [comment]
Thanks for reporting the problem. The syntax highlighting comes from https://github.com/neovimhaskell/haskell-vim

I'd say open the issue there and see what they say.

**Comment by begriffs** [comment]
Multiline comments now work. If you run the haskell-vim-now installer again it'll upgrade itself.
