### ISSUE TITLE
Install & upgrade scripts in Haskell

### ISSUE THREAD

**Issue by SX91** [begriffs/haskell-vim-now#131]
It's certainly possible (to some extent) to rewrite parts of existing bash scripts to Haskell (with Shelly or Turtle libs).
I've made some small sample with Turtle: http://lpaste.net/147775.

It's totally not possible to completely get rid of shell scripts in project (and there's no reason to do that), but wouldn't it be nice to have Haskell IDE installer written in haskell? :D 

Any thoughts? Pros/Cons?

**Comment by begriffs** [comment]
Good point! Bash sucks and we already require Stack to install things. One thing to keep in mind is that `runhaskell` may not be on the user's path. Stack puts it in a location such as `$HOME/.stack/programs/x86_64-osx/ghc-7.10.2/bin/` which depend on the architecture and ghc version. So the shebang at the top of the haskell setup script must refer to `stack path --bin-path` or the startup install script must invoke the setup script by itself finding runhaskell and calling it with the setup script path.

**Comment by begriffs** [comment]
It's working pretty well for now so closing this issue.
