### ISSUE TITLE
Mac OS X: brew install fails

### ISSUE THREAD

**Issue by bjornbm** [begriffs/haskell-vim-now#134]
The `brew install` from `setup.sh` line 22 fails with the following message:

    --- Installing with homebrew...
    Error: No available formula with the name "make"

As a result none of the software in `BREW_LIST` gets installed.

    BREW_LIST="git make vim ctags"

Due to other complaints from `setup.sh` I did a manual install (using homebrew) of vim 7.4 and exuberant ctags. There were no complaints about git or make so I haven't replaced the ones from Apple.

    git version 2.5.4 (Apple Git-61)
    GNU Make 3.81

I'm on Mac OS X 10.11.2 with Xcode 7.2 installed. Perhaps without Xcode I wouldn't have had git and make installed already(?).

As a side note it also seems to me that if this issue is fixed the ctags issue discussed on https://github.com/begriffs/haskell-vim-now/wiki/Installation-Troubleshooting should go away by itself.

**Comment by begriffs** [comment]
Strange, my homebrew knows about make:

```bash
$ brew info make
homebrew/dupes/make: stable 4.1 (bottled)
https://www.gnu.org/software/make/
/usr/local/Cellar/make/4.1 (11 files, 908K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-dupes/blob/master/make.rb
==> Dependencies
Optional: guile ✘
==> Options
--with-default-names
	Do not prepend 'g' to the binary
--with-guile
	Build with guile support
```

If you run `brew update` does it then know how to `brew install make`?

**Comment by bjornbm** [comment]
My homebrew is up to date. This is what I get:
```
➜  ~  brew update && brew install make 
Already up-to-date.
Error: No available formula with the name "make" 
==> Searching for similarly named formulae...
These similarly named formulae were found:
automake             cmake                icmake               makefile2graph       makepkg              premake            
bmake                colormake            libpagemaker         makeicns             makepp               remake             
bsdmake              gnustep-make         makedepend           makensis             makeself             smake              
To install one of them, run (for example):
  brew install automake
==> Searching taps...
These formulae were found in taps:
homebrew/dupes/make                        homebrew/x11/imake                         Caskroom/cask/makemkv                    
homebrew/science/maker                     Caskroom/cask/cmake                        Caskroom/cask/makerbot-desktop           
homebrew/versions/automake112              Caskroom/cask/dataurlmaker                 Caskroom/cask/popmaker                   
homebrew/versions/cmake28                  Caskroom/cask/diskmaker-x                  Caskroom/cask/texmaker                   
homebrew/versions/cmake30                  Caskroom/cask/makehuman                    Caskroom/cask/th-makerx                  
homebrew/versions/cmake31                  Caskroom/cask/makeiphoneringtone           Caskroom/cask/treemaker                  
To install one of them, run (for example):
  brew install homebrew/dupes/make
```

**Comment by bjornbm** [comment]
Reading more closely (sorry): my homebrew also knows of homebrew/dupes/make but only as a "tap" and not as a "formula". Thus, I presume, the following behaviour in contrast to yours:

    ➜  ~  brew info make
    Error: No available formula with the name "make" 

From https://github.com/Homebrew/homebrew-dupes:

Homebrew Dupes
These formulae duplicate software provided by OS X, though may provide more recent or bugfix versions.

> ## How do I install these formulae?
>
>     brew install homebrew/dupes/<formula>
>
> Or `brew tap homebrew/dupes` and then `brew install <formula>`.

I am on a very fresh install of homebrew. Perhaps you have tapped `homebrew/dupes`? Either way, it seems that including the full path in `BREW_LIST` should do the trick:

> BREW_LIST="git homebrew/dupes/make vim ctags"
