### ISSUE TITLE
Paragraph formatting is broken with gq

### ISSUE THREAD

**Issue by begriffs** [begriffs/haskell-vim-now#135]
1. Ensure `par` is installed on system
2. Use it properly -- this is broken

**Comment by azadbolour** [comment]
I did some more fiddling with formatting and found that textwidth (tw) is set to 500 in .vimrc. That is why my gqap was not working. If I set tw=80, I see the formatting work as before. I could not fix the issue by commenting out the par line or altering its width parameter. 

Azad

**Comment by begriffs** [comment]
Note to self: #93 is related when a Haskell buffer is detected.
