### ISSUE TITLE
Complie check working for single files but not in a project 

### ISSUE THREAD

**Issue by mckeankylej** [begriffs/haskell-vim-now#139]
Say I run ",hc" on a file without a stack project structure around it, hdevtools can check the file, but when I run ",hc" on a projects file syntastic says nothing. I ran my compile time check with test = False + 1 which doesn’t type check. If you want I can push the project to github so you can also take a look at how it not working.

**Comment by begriffs** [comment]
I would like to see the project, yes.

I suspect something about the environment might be wrong because I do syntax checking in stack projects all the time.

**Comment by mckeankylej** [comment]
https://github.com/mckeankylej/hchess/tree/v3

I suspect it has something to do with hdevtools, it has always been buggy on my machine.

**Comment by begriffs** [comment]
I cloned the project, ran stack build (which worked), then started editing `src/Board.hs`. When I ran `,hc` it came up with a few warnings lines 17 and 35.

The first thing I would try is running `killall hdevtools` from the terminal, then trying to check a source file again. This will force hdevtools to load fresh and perhaps the newly installed version will load.

If that doesn't work check if you have an old version of hdevtools taking priority on your PATH. Haskell-vim-now compiled a new version and put it in `~/.local/bin/hdevtools`. For me it is version 0.1.2.1.

**Comment by mckeankylej** [comment]
Tried the killall, still didn’t work. Yes there is only one version of hdevtools and its version number is 0.1.2.1. I complied my own version of vim with lua version 7.4 for neocomplete, could that be the issue?

**Comment by begriffs** [comment]
Let's get more of an idea why hdevtools is failing. Try running it by itself on the command line like this (from the hchess project root)

```bash
hdevtools check -g-Wall src/Board.hs
```

Hopefully it will print a helpful error.

**Comment by mckeankylej** [comment]
This is very intresting, because I am using stack I dont require a ghc. Hdevtools now complains about this 

    Cabal error: The program 'ghc' version >=6.4 is required but it could not be found.

**Comment by begriffs** [comment]
Oh OK this makes more sense. Actually stack does use ghc under the hood (it installs versions of ghc as needed). However the ghc installed by stack is not visible to hdevtools which is a standalone server which looks for ghc.

Stack can give you a new path to use in your shell. Try this:

```bash
export PATH=$(stack path --bin-path)
kilall hdevtools
hdevtools check -g-Wall src/Board.hs
```

If this works then it means we have to add another step to the haskell-vim-now installer to adjust the shell search path or tell the user how to do it.

**Comment by mckeankylej** [comment]
Okay yep ,hc works great now this is the solution. Unfortunately ,hl doesn’t work.  I considered closing this issue but I fear the ,hl problem stems from similar errors.

**Comment by begriffs** [comment]
Cool! Glad you reported this because other people will run into the same problem.

Try running hlint from the command line as well to spot any errors it's throwing.

**Comment by mckeankylej** [comment]
I don’t think hlint was downloaded, because when I ran hlint it said program not installed. Then when I looked in my .local/bin there is not executable named hlint.

**Comment by begriffs** [comment]
Uh oh it should have been installed by the h-v-n setup script. Try running the installer again. It should notice hlint is missing and try to build it. We'll then see if it raises any errors.

**Comment by mckeankylej** [comment]
--- <---- HASKELL VIM NOW installation successfully finished ---->

After this message hlint still isn’t installed. Is this an error with the installer? I could build my own hlint if necessary.

**Comment by begriffs** [comment]
What a surprise, I don't see hlint in the list of helpers to install anymore. Just added it back.

Try this one more time: `bash <(curl -sL https://git.io/haskell-vim-now)`

**Comment by mckeankylej** [comment]
Works great now! I went ahead and checked all the commands listened in the read me just to be nice, they seem to be working perfectly! I am excited to use this I hacked together a vim a lot like this and am very tired of maintaining it ;).

**Comment by begriffs** [comment]
Thanks for checking the other commands.

How do you think we should deal with the PATH issue? The installer could append this to `~/.profile`

```bash
export PATH=$(stack path --bin-path)
```

probably grepping the file first to see whether such a line already exists.

**Comment by mckeankylej** [comment]
I already added that line to my ~/.profile. I dont think there is any other way. Why is my machine different from others in this error?

**Comment by mckeankylej** [comment]
Wait this is this a general solution? What if someone is using two different ghcs?

**Comment by begriffs** [comment]
Honestly I think the error you experienced must be widespread. It was masked on my dev machine because Stack's GHC is on my path. I used to have vim using ghc-mod rather than hdevtools but that broke because of Stack and I switched over to the latter. The switch probably broke things for some people. Really glad you submitted the issue. I should make a test suite for this project somehow so I know if things break. Not sure how to do that really.

I also think you're right that the .profile based PATH configuration would not work properly for multiple GHCs across projects. A better way would be to intercept the call to hdevtools from the vim command and prepend it with `PATH=$(stack path --bin-path)` since stack path adjusts its output based on the containing program. This would also avoid polluting a user's general path and surprising them.

**Comment by begriffs** [comment]
OK I've got a possible fix. Try this out for me if you would.

Comment out the path fix you made in .profile and then run

```bash
cd ~/.config/haskell-vim-now
git fetch
git checkout flexible-stack-path
killall hdevtools
```

Now open a new terminal (so that it won't have your old path settings from .profile), go to your project and open vim there. The `,hc` command should work. It should pick the appropriate GHC path for the project.

If this works on your machine then I'll merge it to master.

**Comment by mckeankylej** [comment]
Yep works, checked out the addition too, it is much better form then modifying peoples .profile. That should be for user customization. I say merge this with master.

**Comment by begriffs** [comment]
:+1:
