### ISSUE TITLE
Do we really need exact pointful and pointfree versions?

### ISSUE THREAD

**Issue by SimpleX91** [begriffs/haskell-vim-now#142]
With latest LTS-4.2 helper binaries install without any issues, if you remove version specifiers from pointfree and pointful.
Is there any reason to install exact versions? If not, it's safe to bump resolver to lts-4.2.

BTW, wouldn't it be better to either use user's resolver or build helpers in hvn dir or tmp?

**Comment by begriffs** [comment]
Originally, IIRC, we were in a precarious situation with versions. Maybe now there is an LTS that works great with all our packages.

This highlights a more general problem: we don't have any tests on this project. I bet we could actually run the installer on Circle CI and check that the binaries got installed properly. Then each PR would get tested through continuous integration.

I've also done a poor job creating "versions" of haskell vim now. When someone submits an issue I have no way to assess the state of their system.

Do you think you could help me set up a test suite? (I know it's a lot to ask!) I've just been kind of struggling to manage my time between maintaining various projects. It seems like the kind of change that will make things easier in the long run.

**Comment by jship** [comment]
For reference, bosu/hscope@e34ab96c18926b877652fc37d02ed8e077e8afd0 makes hscope compatible with haskell-src-exts-0.17.*.  hscope was the primary dependency tying haskell-vim-now to a pinned nightly.

If I get a chance tonight, I will test with LTS-4.2 too.  I'd be interested in helping with the test suite, but might not be able to contribute to that for a while.  Any preference of Circle to Travis?

**Comment by begriffs** [comment]
Thanks for testing the LTS!

I've been enjoying Circle lately, but Travis is fine too. Probably whichever one can most easily test across multiple operating systems or docker containers.

**Comment by jship** [comment]
Yes, can confirm that LTS-4.2 and removal of pinned pointful and pointfree works fine.  Created PR.
