### ISSUE TITLE
Errors not finding binaries

### ISSUE THREAD

**Issue by carldong** [begriffs/haskell-vim-now#145]
I suddenly get these errors when I tried to open a haskell file:

```
Error detected while processing function ghcmod#util#check_version[1]..ghcmod#util#ghc_mod_version[2]..vimproc#system[25]..<SNR>118_system[9]..vimproc#pgroup_open[15]..<SNR>118
_pgroup_open[7]..vimproc#plineopen3[6]..<SNR>118_plineopen[50]..<SNR>118_convert_args[21]..vimproc#get_command_name:                                                            
line   15:                                                                                                                                                                      
E605: Exception not caught: vimproc#get_command_name: File "ghc-mod" is not found.                                                                                              
Error detected while processing function ghcmod#util#check_version[1]..ghcmod#util#ghc_mod_version:                                                                             
line    2:                                                                                                                                                                      
E171: Missing :endif                                                                                                                                                            
Error detected while processing /home/carl/.config/haskell-vim-now/.vim/bundle/ghcmod-vim/after/ftplugin/haskell/ghcmod.vim:                                                    
line   31:                                                                                                                                                                      
E171: Missing :endif                                                                                                                                                            
Error detected while processing function <SNR>5_LoadFTPlugin:                                                                                                                   
line   17:                                                                                                                                                                      
E170: Missing :endfor                                                                                                                                                           
Error detected while processing function <SNR>10_lod_ft:                                                                                                                        
line    4:                                                                                                                                                                      
E171: Missing :endif 
```

I tried an update, which did not work. I don't remember doing anything problematic, except that my system upgraded a bunch of haskell packages while I also have a stack installation

**Comment by begriffs** [comment]
If you run the haskell-vim-now installer again does it try to reinstall the binaries?

**Comment by carldong** [comment]
Yes, it did.

**Comment by begriffs** [comment]
I wonder if this is related to the path changes introduced in this PR https://github.com/begriffs/haskell-vim-now/pull/144/files

Also can you check if there are any binaries in your `~/.local/bin`?

**Comment by carldong** [comment]
Yes, all binaries are there

**Comment by jship** [comment]
First, see if the helper binaries are available on the path in Vim.  Try executing these commands in Vim:

```vim
:echo executable('ghc-mod')
:echo executable('hscope')
```

The above should print a '1' in the command bar if the executable is accessible from Vim's path, 0 otherwise.  If it's a '0', you can try the following in Vim:

```
In insert mode, Ctrl-r then =$PATH
```

This will print Vim's path into the current buffer.  From there, you can see if the path info is correct.

You can also do a clean install if you'd rather not investigate the path.  To clean up, close vim and run the following.  Note you might want to backup your local changes if you have any under .config.  Also, if you have any global packages installed via stack, they'll be gone after this.

```bash
rm -fv ~/.codex
rm -rfv ~/.config
rm -rfv ~/.local
rm -rfv ~/.stack
rm -rfv ~/.vim
rm -fv ~/.viminfo
rm -fv ~/.vimrc
```

**Comment by carldong** [comment]
Well, they print 1. Also, I am really hesitate on removing all those configurations

**Comment by jship** [comment]
From the error output above, looks like the ghcmod-vim plugin is getting confused and can't find the ghc-mod executable.  This sounds like a path issue, so if you're not comfortable doing a clean install, would you mind checking the path in vim for correctness?

[This line in .vimrc](https://github.com/begriffs/haskell-vim-now/blob/8921a4501d993cbaf2c8adcfa40c538909a8ebac/.vimrc#L72) might need some exploration if stack is not returning a reasonable path on all platforms.

Are you using custom configurations under .config?  If not, it is safe to remove the above directories and do a fresh install.  You can always back them up before-hand.

**Comment by carldong** [comment]
My config is in .config. Before I clean things, I would point out that nothing is returned when I invoke `:echo $PATH`. I will try a clean install, too

**Comment by carldong** [comment]
I tried a clean install, did not work.

**Comment by jship** [comment]
Maybe this is from the GHC version or the haskell-vim-now helper binaries' versions not matching?  From your package's directory, you could try ```rm -rf .stack-work``` and then rebuilding.

**Comment by carldong** [comment]
It's close, because I just found that opening an hs outside that project does not come with that problem. I removed `.stack_work` but it did not work. It should be a project specific problem, but it still persists.

tree output:

.
├── app
│   ├── Main.hs
│   └── Main.hs~
├── LICENSE
├── README.md
├── README.md~
├── Setup.hs
├── src
│   └── FRP
│       └── Timeless
│           └── Framework
│               ├── Debug.hs
│               ├── SDL
│               │   ├── Components.hs
│               │   ├── Components.hs~
│               │   ├── Events.hs~
│               │   ├── Scene.hs~
│               │   └── Utils.hs
│               ├── SDL.hs
│               ├── SDL.hs~
│               └── UI
│                   ├── Components.hs
│                   ├── Components.hs~
│                   ├── Events.hs
│                   ├── Events.hs~
│                   ├── Scene.hs
│                   └── Scene.hs~
├── stack-3.8.yaml
├── stack.yaml
├── test
│   ├── DejaVuSans.ttf
│   ├── Spec.hs
│   └── test.bmp
├── timeless-SDL.cabal
└── timeless-SDL.cabal~

**Comment by jship** [comment]
Did you rebuild with stack after removing ```.stack-work```?

Might be worthwhile comparing the Stackage snapshot in ```~/.stack/global-project``` with the one you are using in your package.

**Comment by carldong** [comment]
No, I did not rebuild. And up on trying, I found 

    AesonException "Error in $.extra-deps: failed to parse field 'extra-deps': failed to parse field extra-deps: expected [a], encountered Null"

I will fix that and see

**Comment by carldong** [comment]
And it is fixed. Although it is not a good idea to have the editor stop working when the project is misconfigured
