### ISSUE TITLE
Syntastic drops support for ghc-mod 5.4.0 and later.

### ISSUE THREAD

**Issue by SimpleX91** [begriffs/haskell-vim-now#148]
https://github.com/scrooloose/syntastic/commit/544acba17dbc72ca84951c29d774e317914d8a0d

Due to that change, I think we should either patch Syntastic to work with newer ghc-mod or replace it with other checker tool (like NeoMake).

I've been using neomake for some time, it works good enough, but doesn't have error position highlighting (only line, not columns). But it's definitely better for neovim due to asynchronous jobs dispatch.
If you're interested, I'll make a patch.

**Comment by begriffs** [comment]
Sounds good to me. Then we can get rid of the ghc-mod/hdevtools split we're using right now and go back to 100% ghc-mod. It would also mean we can remove the slow `let $PATH=system('stack path --bin-path')` thing from startup.

Thanks for your help.
