### ISSUE TITLE
ghc-mod type does not work without GHC_PACKAGE_PATH

### ISSUE THREAD

**Issue by harendra-kumar** [begriffs/haskell-vim-now#156]
`,ht` and `,hT` were not working in my setup, the only ghc that I have is the one installed by stack (no system installed ghc). I tried to run `ghc-mod type` from command to see what's going on and it gave me:

```
EXCEPTION: types:
           Could not find module ‘Turtle’
           Use -v to see a list of the files searched for.
           Could not find module ‘Data.Text’
           Perhaps you meant Data.Set (from containers-0.5.6.2)
           Use -v to see a list of the files searched for.
```

So I figured that we need GHC_PACKAGE_PATH. With `export GHC_PACKAGE_PATH=$(stack path --ghc-package-path) ` in my .bash_profile everything started working fine. 

So I tried to put `let $GHC_PACKAGE_PATH=system('stack path --ghc-package-path')` in .vimrc but strangely it did not work even though `echo $GHC_PACKAGE_PATH` showed perfectly good path. Not sure what's wrong with that. 

But anyway that would have added more startup delay. So I now have PATH and GHC_PACKAGE_PATH both set by stack in my .bash_profile instead.

Now, what should be the solution for haskell-vim-now? Should we have something hooked into .bash_profile or try to look into why setting it from .vimrc does not work?

**Comment by begriffs** [comment]
Are you still using haskell-vim-now? If so try running the installer again to update your setup. It may work now.

**Comment by harendra-kumar** [comment]
Not sure what changed, I am not able to reproduce the problem anymore. `ghc-mod` is working fine even without GHC_PACKAGE_PATH. Maybe because of a newer stack version.
