### ISSUE TITLE
Colorscheme/Syntax Highlight does not work on NeoVim

### ISSUE THREAD

**Issue by carldong** [begriffs/haskell-vim-now#157]
It looks like `wombat256mod` does not show any highlighting on NeoVIM. I have checked all conditions and they are the same for Vim. However, running `:hi` reveals that basically every single `xxx` is white. `hi clear` and `syntax reset` resets to default, and color works. I am not sure whether it is because of terminal configuration, because Vim works. 

Possible useful info:

Both Vim and NeoVim: `echo $TERM` returns `xterm`
Vim: `set term=xterm`
NeoVim: there is no `set term`

**Comment by begriffs** [comment]
Thanks for the update. Closing this issue.
