### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by real-or-random** [begriffs/haskell-vim-now#158]
```
--- Installing helper binaries...
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      cabal-helper: needed (<0.7 && >=0.6.3.0), 0.6.1.0 found (latest applicable is 0.6.3.1)
    needed for package ghc-mod-5.5.0.0
*** Binary installation failed with error 1. Aborting...
```

Using resolver lts-5.4 instead of lts-5.2 works fine for me. But I'm not sure if it's just some local issue.

**Comment by SimpleX91** [comment]
Remove additional packages from `~/.stack/global-project/stack.yaml` (or something like that). We don't need them anymore, you need to remove them manually. Then try again (with lts-5.2).

**Comment by real-or-random** [comment]
Thanks. :)

I had the following:
```
packages: []
extra-deps: [cabal-helper-0.6.1.0, pure-cdb-0.1.1]
```

So cabal-helper in extra-deps was the issue (not in packages). 

I had removed the whole `stack.yaml` and then tried with the most recent lts. But I see, it works with lts-5.2 too.

**Comment by SimpleX91** [comment]
Reopen the issue, please.
We need some message in the end of installation about extra-deps.

**Comment by begriffs** [comment]
Could/should we do an automated `sed` on the yml file to fix it?

**Comment by real-or-random** [comment]
I think that's the way to go but an additional confirmation by the user could be a good idea.

By the way, I'm not sure whether pure-cdb was added by installing HVM or by some other package.

**Comment by jship** [comment]
pure-cdb is a transitive dependency for haskell-vim-now because of hscope (at least).  pure-cdb is on LTS now, so haskell-vim-now doesn't have to do anything special for it.  See beb8ee05f3c54072fc98c1b6b30a1eadbcac081a.
