### ISSUE TITLE
Symbols replacements

### ISSUE THREAD

**Issue by raynerd** [begriffs/haskell-vim-now#159]
First I have to say, great job. I'm opening this issue because I don't like the symbols replacement eg. -> to → or <>  to ⊕. It's a way to disable this feature?. Thanks

**Comment by begriffs** [comment]
Yeah people are kind of 50/50 love-hate on the concealments.

To customize them edit `~/.config/haskell-vim-now/.vimrc.local` and include

```viml
let hscoptions="STRING"
```

Where `STRING` determine which symbols are concealed. This documentation explains the options:
https://github.com/enomsg/vim-haskellConcealPlus#available-options

**Comment by ptkato** [comment]
Did something change? I tried to disable all the concealing by writing `let hscoptions="qxes...BQZa"` into `~/.config/haskell-vim-now/vimrc.local` and nothing changed.

Is there a way to disable this plugin completely, without the need of writing all those characters down?

**Comment by begriffs** [comment]
You can set

```viml
let g:no_haskell_conceal = 1
```

to disable concealment entirely. Just tried it in my own vimrc.local and it worked. (You do have `:source` your vimrc or restart vim for it to take effect)

**Comment by arbitary** [comment]
Thanks

**Comment by tsoernes** [comment]
Note that `hscoptions` should be set in `~/.config/haskell-vim-now/vimrc.local` not `.vimrc.local` (small typo there!)
