### ISSUE TITLE
Do not encourage users to pipe to bash

### ISSUE THREAD

**Issue by phanimahesh** [begriffs/haskell-vim-now#160]
README contains `bash <(curl -sL https://git.io/haskell-vim-now)`
Piping code to shell is bad&trade;

Atleast provide hashes and encourage users to check the hash before executing the install script.

Even if network and the script can fully be trusted, if network transfer breaks while a relatively harmless line like `rm -r /tmp/...` is being transferred immediately after `rm -r /`, the partially piped input will be evaluated by bash and do bad things&trade;. This is a hypothetical scenario, yes, but I was told haskell-land takes safety seriously.

Can it be changed to
```sh
curl -L https://git.io/haskell-vim-now > /tmp/haskell-vim-now.sh
bash /tmp/haskell-vim-now.sh
```
It is no longer a one-liner, but is much safer. Only the source and network have to be trusted now and bad luck can't do much damage.

It would be great if you can also publish md5/sha hashes and encourage users to verify them.

**Comment by begriffs** [comment]
Good to know. I copied the style of other installers I've seen online but happy to change things to make it more trustworthy. How do people typically document the md5 checksums of downloads? Should I add a note in the readme and keep it up to date? Something like this:

```bash
curl -L https://git.io/haskell-vim-now > /tmp/haskell-vim-now.sh
md5 /tmp/haskell-vim-now.sh
# should be 8450eab894ab9ea65362ac23a0118277
bash /tmp/haskell-vim-now.sh
```

**Comment by phanimahesh** [comment]
It would be really awesome if you can PGP sign the scripts. (You'll have to use detached signatures and publish the key id and signatures along with installer script.)

Checksums in MD5, SHA256, and PGP signatures are all commonly published for security conscious projects. For example distributions such as Debian, CentOS provide both md5 checksums and PGP signatures and let users choose.

Examples:
Debian: [CD Images](https://www.debian.org/CD/verify), [Apt packages](https://wiki.debian.org/SecureApt#Secure_apt_groundwork:_checksums)
CentOS: [rpm packages](https://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-check-rpm-sig.html)

Adding a simple comment like the one you showed works great. Additional explanatory comments may be useful.
```sh
# Download the installer
curl -L https://git.io/haskell-vim-now > /tmp/haskell-vim-now.sh
# Optional but recommended: Verify the installer
# should output 8450eab894ab9ea65362ac23a0118277
md5 /tmp/haskell-vim-now.sh
# Run the installer
bash /tmp/haskell-vim-now.sh
```

Aside: You may find [hashpipe](https://github.com/jbenet/hashpipe) interesting.

**Comment by begriffs** [comment]
@phanimahesh I'd like to start signing the installer but have some questions

* What's the most convenient procedure to tell people to verify the signed file? I've published my public key at https://begriffs.com/pgp.asc and on hkps://hkps.pool.sks-keyservers.net
* When I verify the file myself it succeeds but warns me that "This key is not certified with a trusted signature!" What's up with that?
* When I get pull requests that update the installer do I merge them and then quickly make a commit to update the detached signature?

**Comment by phanimahesh** [comment]
- If you have a key published and sign the installers with it, it works great.
 - PGP keys have a notion of trust. If I know you, and know that you are really the owner of a key, I can sign your key with mine and publish the signature to any keyserver. If someone else downloads your key but don't know you personally, they need a way to verify the key really belongs to you. Anyone can publish a key with your name and email on it, so verification becomes important. When out-of-band verification is not possible PGP tries to see if someone you already trust has verified this key with a signature. The error you get is because you have neither set a trust on the key manually nor have any signatures which can be used to automatically verify it.
 - When you get git pull requests, on the command line you can do `git merge --no-commit` which performs a merge but stops just before making an automatic merge commit. You can update the signature, `git add` it and then `git commit`. This creates a merge commit as usual but with the updated signature. This ensures that there are no "bad" commits in your history - every commit on master has a valid signature.

**Comment by SX91** [comment]
We could remove migration part from install.sh, this would be enough, really. This script won't even execute on DL failure, just look inside. Everything else is under Git.
Signature would be an overkill.

But at least separation of download and execution parts would be a good thing. Piping directly to bash is bad :)

**Comment by phanimahesh** [comment]
My initial request was to just separate the download and execution, and optionally include a hashsum. Signatures were an option @begriffs suggested, and providing additional verification options is always a good idea IMO.

It is very subjective, but yes, most installers online don't publish hashsums or signatures, and hence they may seem overkill. I don't really think so. Provided they can be maintained up to date, it would simply be encouraging better practices.

**Comment by begriffs** [comment]
Using md5 might be easier than pgp signature because any contributor could generate it and we could add a check in CI to be sure they did.

**Comment by phanimahesh** [comment]
@begriffs Yes, that sounds good.

**Comment by begriffs** [comment]
Where would you recommend we publish the md5 hash? Ideally I could add a commit hook to keep it up to date.

**Comment by phanimahesh** [comment]
As a comment in installation instructions in README would be best from usability perspective. But that'll mean writing a slightly ugly commit hook.

maybe something as simple as a `# MD5SUM:` line in the README, and a pre-commit hook that'll do a replacement of the line (using sed/awk) with correct md5? We can then ask Travis to make a new commit if anyone pushes without updating md5 and the hashes differ.

**Comment by begriffs** [comment]
Started looking into this today...it's kind of a lot of work. What about a simple comment like

```bash
bash <(curl -sL https://git.io/haskell-vim-now)
# or if you're cautious, download the script and inspect it first
```

Although a cautious person would probably do that anyway.

I'm happy to add the MD5 stuff if you want to send a pull request to implement it, otherwise I'm going to punt and add a comment or just leave things as they are.
