### ISSUE TITLE
How can I make ,hc to show ghcmod errors in several lines?

### ISSUE THREAD

**Issue by oscarvarto** [begriffs/haskell-vim-now#162]
This is a question rather than an issue. How can I customize the height of the area where ghc-mod shows the errors?

![ghcmoderror](https://cloud.githubusercontent.com/assets/1676245/14063738/c2f1805e-f39b-11e5-9947-faf3afd4033b.png)

The error at the bottom is not shown complete. Is it possible to see more of it, maybe even scrolling through the error message?

Thanks for any guidance, pointers.

**Comment by begriffs** [comment]
Internally it uses neomake, so try running `:lopen` to see the list of errors.

Some other shortcuts
* `:ll` to jump to the first error
* `:ll 3` (for instance) jump to the third error

I think I could add
```viml
let g:neomake_open_list = 2
```
to make neomake open the error window automatically when an error is found. Would you prefer that behavior?

**Comment by oscarvarto** [comment]
Thanks for helping me. I have added the option to my vimrc.local and tried. For me, it's better with your suggestion.

I appreciate the pointer to neomake. Now I know where to read by myself. I'm new to both vim and haskell, so imagine how much your work and guidance is useful to me :)
