### ISSUE TITLE
Mac OS X: brew install fails

### ISSUE THREAD

**Issue by mikowiec** [begriffs/haskell-vim-now#166]
Preconditions:
  mac OSX: 10.9.2
  Homebrew 0.9.9 (git revision 1451; last commit 2016-04-23)
  The Glorious Glasgow Haskell Compilation System, version 7.10.3
  cabal-install version 1.22.6.0
  stack: Version 1.0.4.3 x86_64

Next logs obtained after installation "bash <(curl -sL https://git.io/haskell-vim-now)":
--- Installing with homebrew...
Error: No available formula with the name "homebrew/dupes/make" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
--- Testing for broken Ruby interface in vim...
--- Test passed. Ruby interface is OK.
--- Checking ctags' exuberance...
../Xcode62.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
*** Requires exuberant-ctags, not just ctags.

I've performed installation of brew make next way:
"brew install https://raw.githubusercontent.com/Homebrew/homebrew-dupes/master/make.rb"
and "brew info make": 
  make: stable 4.1 (bottled)

But result for "haskell-vim-now" installation did not complete.

**Comment by mikowiec** [comment]
Issue resolved:
It's necessary to put next lines:
sudo brew tap homebrew/dupes
brew install homebrew/dupes/make

There is not permission for "brew tap" without sudo.

**Comment by begriffs** [comment]
You're saying we should modify setup.sh and add a brew tap before the line linked below? https://github.com/begriffs/haskell-vim-now/blob/master/scripts/setup.sh#L50

**Comment by mikowiec** [comment]
The issue was related to admin permission for "brew tap homebrew/dupes" command.
