### ISSUE TITLE
There is no warning that installing will remove all previous Vim plugins etc.

### ISSUE THREAD

**Issue by Cypher1** [begriffs/haskell-vim-now#170]
It would be great if the installation didn't remove all the other settings and plugins etc. but most importantly the readme doesn't say anything about it which is downright dangerous!

**Comment by begriffs** [comment]
What do you think we should add to the readme? The first paragraph says

> Don't worry, it backs up your original configuration to `~/.config/haskell-vim-now/backup/.vimrc.yearmonthdate_time`

**Comment by begriffs** [comment]
(Also sorry for messing your vim configuration up unexpectedly)

**Comment by Cypher1** [comment]
It deleted all my actual bundles though (had to reinstall them) and didn't
copy my .vimrc (fortunately that may have been because it was a symlink to
a git repo that I could restore it from).

All the other plugins I have used have not needed to mess with any of my
other configuration. Having that as an option here would be great.

**Comment by SimpleX91** [comment]
HVN is not a plugin, it's an environment for Haskell development. So it's not trivial to make it co-exist with user's VIM config (if even possible).
If @Cypher1 have any suggestions on how to make HVN less invasive, go ahead and share with us! =)

**Comment by Cypher1** [comment]
Oh. Really it's an environment? That would be good to have know. Woops.
(Thank you)
