### ISSUE TITLE
General repo cleanup

### ISSUE THREAD

**Issue by SX91** [begriffs/haskell-vim-now#176]
There's quite a lot of issues (+1 btw :smile:) and branches we don't need.
I suggest clearing them (so many issues demotivates user from making a new one).

**Comment by begriffs** [comment]
Yeah I closed some of them a day or two ago and I'll purge the rest over the weekend.

**Comment by begriffs** [comment]
Thanks for the nudge to clean up the issues. The remaining ones are either still valid, awaiting updates from their submitters, or covered by open pull requests.
