### ISSUE TITLE
"Rebuild project with Cabal's --enable-test flag"

### ISSUE THREAD

**Issue by isheff** [begriffs/haskell-vim-now#180]
Sorry, not sure if this is the correct forum in which to ask, but I'm a relatively new stack user and I'm trying to get haskell-vim-now to be able to guess types in my large haskell project. Right now, it can't guess anything. The wiki says:

"This relies on your project being built with Cabal's --enable-test flag. You may need to recreate your sandbox and rebuild with this option."

I'm not entirely sure how to do this. I've tried doing a fresh rebuild (package.cabal and stack.yaml retained, but nothing compiled), with 

stack build --flag *:--enable-test

but it still can't guess any types. I'm not sure what to do.

**Comment by begriffs** [comment]
Try `stack build --test --no-run-tests`. It's weird that ghc-mod can't guess any types, so I'm not sure that this will solve the problem but give it a try and let me know what happens.

**Comment by isheff** [comment]
I'm afraid it produced no change.

**Comment by isheff** [comment]
My attempts to reproduce the problem in a simple project and create a minimal working example have failed, so here are some steps to reproduce:

```
$ git clone git@github.com:buckie/juno.git
$ cd juno/
$ stack setup
$ stack  build --test --no-run-tests
$ vim src/Juno/Messaging/ZMQ.hs  # chosen pretty much arbitrarily
:33
,ht
:34
2w
,ht
```
It spits out ```ghcmod#command#type: Cannot guess type``` both times.

other stuff, like 
```
,tg
:34
0
3w
C-\
```
works just fine.

**Comment by isheff** [comment]
So, am I just barking up the wrong tree, or missing something?

**Comment by begriffs** [comment]
I'll make a todo for myself to look into this problem some more.

**Comment by isheff** [comment]
Is there something I can do to help?

**Comment by begriffs** [comment]
Sorry to leave you hanging on this one! Been preoccupied with some other things. One thing you could try is to create a virtual machine or a server on EC2/Digitalocean and install Stack and haskell-vim-now there. Then clone your project and try to build it on the server. See if vim can guess the types. If it works on the server then maybe there is more to investigate about your machine configuration.

**Comment by isheff** [comment]
I have been trying to replicate the bug in a VM, but find myself unable to install haskell-vim-now due to a "stack paths" issue, which I've posted at https://github.com/begriffs/haskell-vim-now/issues/130

**Comment by begriffs** [comment]
I merged a PR that should acommodate older stack options. Can you try again?

**Comment by begriffs** [comment]
@isheff ping

**Comment by isheff** [comment]
I have been able to replicate this bug on a fresh Ubuntu virtual machine, and indeed am unable to guess types in the "juno" project.

This is an Ubuntu 16.0.4 VM, and the only things I've done on it are install juno from https://github.com/kadena-io/juno , as well as its prerequisites, run stack upgrade, downloaded haskell-vim-now, compiled everything, opened a file, and tried to guess a type. 

user: user
password: xyzzy

The relevant vm is "Cannot_Guess_Type" 
Sync: https://link.getsync.com/#f=VM&sz=56E8&t=1&s=JWLRXPY77NRLL2CNEWVSGCBFRKYZ74VH&i=CAYIGCJOAU2JW72AAHQWOUQ22B3CNVWZJ&v=2.3
Google Drive (available soon): https://drive.google.com/open?id=0B5fhtA7wViuec2o1Y2NudzRVYXc

**Comment by begriffs** [comment]
OK I learned something new that may help. I suspect the GHC version used to build ghc-mod does not match the GHC version used to build your code (as explained here https://github.com/DanielG/ghc-mod/wiki#readpackagedb-inappropriate-type)

From inside your project directory try running

```bash
ghc-mod --version
stack ghc -- --version
```

If the GHC versions don't match up then I'll tell you what to do next to fix it. Once we get it working for you then I can update the Wiki.

**Comment by begriffs** [comment]
I think that will solve your problem. Closing this issue on github. Reopen if my solution doesn't help.
