### ISSUE TITLE
Vim rc Error

### ISSUE THREAD

**Issue by suzumiyasmith** [begriffs/haskell-vim-now#182]
![hvime](https://cloud.githubusercontent.com/assets/7271642/16142247/92229b9c-345b-11e6-93fe-476aecdbf881.png)

I am using manjaro xfce, system ghc and fish.

**Comment by begriffs** [comment]
Interesting, I don't see that color in the haskell-vim-now vimrc or in the wombat color scheme. Maybe you should file this bug with https://github.com/neomake/neomake

**Comment by suzumiyasmith** [comment]
I simply comment the highlight function line(line 20) in the neomake plugin file (haskell-vim-now/.vim/bundle/neomake/plugin/neomake.vim ) to solve this error, and the side effect is acceptable.
I can not configure why `call neomake#signs#DefineHighlights()` causes the problem.
