### ISSUE TITLE
Why is ruby needed?

### ISSUE THREAD

**Issue by jship** [begriffs/haskell-vim-now#190]
Curious why ruby is needed.  Is it a plugin under the hood that depends on it?

**Comment by begriffs** [comment]
I think ruby is not needed, but if vim was compiled with ruby support we check that the installation works with vim. See 0e5e885fad91dc55ad791851f686dae9b5e414ae for this refinement (it was carried along in f9e73372e678723a4412c7477def5d6e90f84c41). I honestly don't remember the context for this check. I think a plugin broke on someone's machine and we discovered it was a ruby misconfiguration. Perhaps @SX91 remembers the context.

**Comment by SX91** [comment]
https://github.com/begriffs/haskell-vim-now/pull/88 @begriffs here it is.

Ruby is not needed, but if vim is compiled with broken ruby support, vim would crash on PlugUpdate (or Upgrade, or whatever). That's why this check's been added.

**Comment by jship** [comment]
Thanks!
