### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by askoufis** [begriffs/haskell-vim-now#191]
I have nothing against haskell-vim-now, but it's just not for me. I was wondering what I'd need to do  to get back to just a stock vim installation?

**Comment by begriffs** [comment]
No problem, it's easy to uninstall.

```bash
ls -alh ~/.config/haskell-vim-now/backup
```

You'll see timestamped `.vim` and `.vimrc` files. Your old configuration will be one of those (there will probably be only one in your case).

```bash
# remove the symlinks which point to haskell-vim-now stuff
rm ~/.vim ~/.vimrc
# now restore the backup
mkdir -p ~/.vim
cp -R ~/.config/haskell-vim-now/backup/.vim.2016xxxx_yyyyyy ~/.vim
cp ~/.config/haskell-vim-now/backup/.vimrc.2016xxxx_yyyyyy ~
```

**Comment by askoufis** [comment]
Thanks a lot!
