### ISSUE TITLE
Not install completelly on Linux Mint 17.3

### ISSUE THREAD

**Issue by Hygens** [begriffs/haskell-vim-now#193]
josenildo@josenildo-HP ~ $ bash /tmp/haskell-vim-now.sh
--> No previous installations detected.
--- Installing Haskell-Vim-Now from https://github.com/begriffs/haskell-vim-now.git ...
Cloning into '/home/josenildo/.config/haskell-vim-now'...
remote: Counting objects: 891, done.
remote: Total 891 (delta 0), reused 0 (delta 0), pack-reused 891
Receiving objects: 100% (891/891), 296.19 KiB | 381.00 KiB/s, done.
Resolving deltas: 100% (548/548), done.
--- Installing system package dependencies...
--- Installing with homebrew...
Warning: git-2.10.0 already installed
Warning: homebrew/dupes/make-4.2.1 already installed
Warning: vim-8.0.0002 already installed
Warning: ctags-5.8_1 already installed
Warning: par-1.52 already installed
--- Checking ctags' exuberance...
ctags: Warning: regcomp ^[ t]*(([A-Za-z0-9_-]+[ tn,]+)+){: Unmatched \{
--- Setting git to use fully-pathed vim for messages...
--- Testing for broken Ruby interface in vim...
--- Test passed. Ruby interface is OK.
--- Installing vim-plug
######################################################################## 100.0%
--- Backing up current vim config using timestamp 20160917_130207...
	/home/josenildo/.config/haskell-vim-now/backup/.vim.20160917_130207
	/home/josenildo/.config/haskell-vim-now/backup/.vimrc.20160917_130207
--- Creating vim config symlinks
	~/.vimrc -> /home/josenildo/.config/haskell-vim-now/.vimrc
	~/.vim   -> /home/josenildo/.config/haskell-vim-now/.vim
--- Installing plugins using vim-plug...

make -f make_unix.mak
make[1]: Entering directory '/home/josenildo/.config/haskell-vim-now/.vim/bundle/vimproc.vim'
cc -W -O2 -Wall -Wno-unused -Wno-unused-parameter -std=gnu99 -pedantic -shared -fPIC  -o lib/vimproc_linux64.so src/proc.c -lutil
make[1]: Leaving directory '/home/josenildo/.config/haskell-vim-now/.vim/bundle/vimproc.vim'
 
--- Setting up GHC if needed...
	Stack bin path: /home/josenildo/.local/bin
	Stack global path: /home/josenildo/.stack
	Stack global config location: /home/josenildo/.stack/global-project/stack.yaml
	Stack resolver: lts-4.0
	/home/josenildo/.config/haskell-vim-now/.stack-bin -> /home/josenildo/.local/bin
--- Installing helper binaries...
Plan construction failed.
*** Binary installation failed with error 1.
*** Aborting...

I have attempted include change resolver for lts-4.0(GHC 7.10.3), but without success.
Some have resolved that?

**Comment by Hygens** [comment]
Too not install on Vagrant virtual Ubuntu/Wily64 image clean without any software installed. The error here is: 
vagrant@vagrant-ubuntu-wily-64:~$ bash /tmp/haskell-vim-now.sh
--> Existing Haskell-Vim-Now installation detected at /home/vagrant/.config/haskell-vim-now.
--- Syncing Haskell-Vim-Now with upstream...
Current branch master is up to date.
--- Installing system package dependencies...
--- Installing with apt-get...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Skipping exuberant-ctags, it is already installed and upgrade is not set.
Skipping make, it is already installed and upgrade is not set.
Skipping vim, it is already installed and upgrade is not set.
Skipping par, it is already installed and upgrade is not set.
Skipping git, it is already installed and upgrade is not set.
Skipping libcurl4-openssl-dev, it is already installed and upgrade is not set.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--- Checking ctags' exuberance...
--- Setting git to use fully-pathed vim for messages...
--- Backing up current vim config using timestamp 20160916_194622...
	/home/vagrant/.config/haskell-vim-now/backup/.vim.20160916_194622
	/home/vagrant/.config/haskell-vim-now/backup/.vimrc.20160916_194622
--- Creating vim config symlinks
	~/.vimrc -> /home/vagrant/.config/haskell-vim-now/.vimrc
	~/.vim   -> /home/vagrant/.config/haskell-vim-now/.vim
--- Installing plugins using vim-plug...
--- Setting up GHC if needed...
	Stack bin path: /home/vagrant/.local/bin
	Stack global path: /home/vagrant/.stack
	Stack global config location: /home/vagrant/.stack/global-project/stack.yaml
	Stack resolver: lts-7.0
	/home/vagrant/.config/haskell-vim-now/.stack-bin -> /home/vagrant/.local/bin
--- Installing helper binaries...
Plan construction failed.
*** Binary installation failed with error 1.
*** Aborting...

**Comment by begriffs** [comment]
Thanks for filing this issue. I suspect that one of these packages fails to install on LTS-4:

```
ghc-mod hlint hasktags codex hscope pointfree pointful hoogle hindent apply-refact
```

Can you try selecting an earlier LTS version in your global stack config (which you can find using `stack --verbosity 0 path --config-location`) and running the installer again?

**Comment by Hygens** [comment]
Hi,


Solved differently.

I have changed for LTS-6.17 erase all folders (.stack, .ghc, .cabal, 
.config/haskell-vim-now).

Restarted script haskell-vim-now and when error I continue via stack 
install not cabal install

and after that tested and at now all functioning.

I will be continue testing that week because I need prepare material for 
one lecture day 09/28/2016.

If not have any problem I will be post there that informations for 
persons that need urgently solutions

that resolve for while.


Thank you,

Josenildo(Hygens)

**Comment by begriffs** [comment]
Good, I'm happy you found a solution. Should we change the installer to deal with this situation do you think?

**Comment by Hygens** [comment]
Hi,

I thinsk it's possible after more tests for validate if all resources 
are functioning but depends too time for that.

Wait please some days.

Thank you,

Josenildo(Hygens)

**Comment by Hygens** [comment]
Hi,

One detail up now I have observed is one problem for hindent not working 
as expected since
exists some detail here. I will go analyse that and correct before continue.

Thanks you,
Josenildo(Hygens)
