### ISSUE TITLE
macOS Sierra install fails on dyld error

### ISSUE THREAD

**Issue by edyu** [begriffs/haskell-vim-now#197]
--> Existing Haskell-Vim-Now installation detected at /Users/ed/.config/haskell-vim-now.
--- Syncing Haskell-Vim-Now with upstream...
Current branch master is up to date.
--- Installing system package dependencies...
--- Installing with homebrew...
Checking out v1.0.1 in /usr/local/Homebrew...
To checkout v1.0.1 in /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git checkout v1.0.1
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
packer                               slimerjs                             voldemort                            zplug                              

Warning: git-2.10.0 already installed
Warning: homebrew/dupes/make-4.2.1 already installed
Warning: vim-8.0.0005 already installed
Warning: ctags-5.8_1 already installed
Warning: par-1.52 already installed
--- Checking ctags' exuberance...
--- Setting git to use fully-pathed vim for messages...
--- Testing for broken Ruby interface in vim...
--- Test passed. Ruby interface is OK.
--- Backing up current vim config using timestamp 20160921_220237...
	/Users/ed/.config/haskell-vim-now/backup/.vim.20160921_220237
	/Users/ed/.config/haskell-vim-now/backup/.vimrc.20160921_220237
--- Creating vim config symlinks
	~/.vimrc -> /Users/ed/.config/haskell-vim-now/.vimrc
	~/.vim   -> /Users/ed/.config/haskell-vim-now/.vim
--- Installing plugins using vim-plug...
--- Setting up GHC if needed...
dyld: malformed mach-o: load commands size (38712) > 32768
/Users/ed/.config/haskell-vim-now/scripts/setup.sh: line 20: 23726 Abort trap: 6           stack setup --verbosity warning
*** Stack setup failed with error 134.
*** Aborting...

**Comment by edyu** [comment]
not sure whether this is helpful: https://stackoverflow.com/questions/39381754/malformed-mach-o-image-symbol-table-underruns-linkedit

**Comment by begriffs** [comment]
Looks like a manifestation of https://github.com/commercialhaskell/stack/issues/2577 -- I think we'll have to wait for this to be fixed upstream.

**Comment by edyu** [comment]
seems to work now.

**Comment by begriffs** [comment]
Glad to hear it. I'll close the issue for now and we can reopen if it comes back.
