### ISSUE TITLE
Install fails with lts-7.0

### ISSUE THREAD

**Issue by mayeranalytics** [begriffs/haskell-vim-now#199]
[ LTS Haskell 7.0 (gcc-8.0.1)](https://www.stackage.org/lts-7.0) just came out and unfortunately this now seems to mean that haskell-vim-now does not install properly anymore. (I was able to trace the problem to the [codex](https://github.com/aloiscochard/codex) package, see [issue 63](https://github.com/aloiscochard/codex/issues/63#issuecomment-248896302)).

Here's where I think `haskell-vim-now` has a bug: Even if I carefully setup the global stack project (`.stack/global-project/`) to use LTS-6.12 via

```
stack --resolver lts-6.12 setup
```

so that I can successfully install the codex package via

```
stack --resolver lts-6.12 install codex
```

I still have a failure of 

```
bash /tmp/haskell-vim-now.sh
``` 

as follows:

```
...
...
--- Setting up GHC if needed...
Downloaded ghc-8.0.1.                                      
Installed GHC.                                                                 
	Stack bin path: /Users/mmayer/.local/bin
	Stack global path: /Users/mmayer/.stack
	Stack global config location: /Users/mmayer/.stack/global-project/stack.yaml
	Stack resolver: lts-7.0
	/Users/mmayer/.config/haskell-vim-now/.stack-bin -> /Users/mmayer/.local/bin
--- Installing helper binaries...
Plan construction failed.
*** Binary installation failed with error 1.
*** Aborting...
```

Somehow the scripts pick up LTS-7.0 (ghc-8.0.1) along the way, and the installation fails.

I'm using a clean Ubuntu VM, and I have the same issue on Mac OS X.

**Comment by bitemyapp** [comment]
This is fixed as far as codex is concerned, I believe: https://github.com/aloiscochard/codex/issues/63#issuecomment-248936267

**Comment by j127** [comment]
I had the "Binary installation failed with error 1." error during installation:

Running this:

    $ stack --resolver lts-6.12 setup

and then editing a line in `~/.stack/global-project/stack.yml` to lts-6.12:

    resolver: lts-6.12

 the installation then worked.

**Comment by SX91** [comment]
I think we once again need `extra-deps` section: `extra-depx: [codex-0.5.0.2]`.
