### ISSUE TITLE
Disable background colour

### ISSUE THREAD

**Issue by ptkato** [begriffs/haskell-vim-now#200]
Is there a way to disable background colours? My terminal is transparent and I see no use to have a solid background colour.

**Comment by begriffs** [comment]
Try adding this to ~/.config/haskell-vim-now/vimrc.local:

```viml
hi NonText ctermbg=NONE
hi Normal guibg=NONE ctermbg=NONE
```

Then restart vim.

**Comment by ptkato** [comment]
It mostly worked, but the line numbers still have a background colour.

**Comment by begriffs** [comment]
Probably need to do

```viml
hi LineNr guibg=NONE ctermbg=NONE

" ...and clear the bg for the gutter too while you're at it
hi SignColumn guibg=NONE ctermbg=NONE
```
