### ISSUE TITLE
Installing helper binaries failed, Arch Linux

### ISSUE THREAD

**Issue by Weznon** [begriffs/haskell-vim-now#205]
weznon ~ $ bash /tmp/haskell-vim-now.sh
ENV: [HVN_INSTALL_BASIC=]
--> Existing Haskell-Vim-Now installation detected at /home/weznon/.config/haskell-vim-now.
--- Syncing Haskell-Vim-Now with upstream...
Current branch master is up to date.
--- Installing system packages [] using [OTHER]...
--> No package manager detected. You may need to install required packages manually.
--- Checking ctags' exuberance...
--- Setting git to use fully-pathed vim for messages...
--- Testing for broken Ruby interface in vim...
--- Test passed. Ruby interface is OK.
--- Backing up current vim config using timestamp 20161014_232627...
	/home/weznon/.config/haskell-vim-now/backup/.vim.20161014_232627
	/home/weznon/.config/haskell-vim-now/backup/.vimrc.20161014_232627
--- Creating vim config symlinks
	~/.vimrc -> /home/weznon/.config/haskell-vim-now/.vimrc
	~/.vim   -> /home/weznon/.config/haskell-vim-now/.vim
--- Installing plugins using vim-plug...
--- Setting up GHC if needed...
	Stack bin path: /home/weznon/.local/bin
	Stack global path: /home/weznon/.stack
	Stack global config location: /home/weznon/.stack/global-project/stack.yaml
	Stack resolver: lts-7.3
	/home/weznon/.config/haskell-vim-now/.stack-bin -> /home/weznon/.local/bin
--- Installing helper binaries...
Plan construction failed.
*** Binary installation failed with error 1.
*** Aborting...

Same issue as #195, just on a different OS

**Comment by begriffs** [comment]
I think PR #203 will fix this. Merging it has been delayed by a somewhat unrelated issue with continuous integration.

**Comment by michaellindon** [comment]
Hi Joe, love the repository, I also have the same issue:

`[michael@michael ~]$ bash /tmp/haskell-vim-now.sh
ENV: [HVN_INSTALL_BASIC=]
--> Existing Haskell-Vim-Now installation detected at /home/michael/.config/haskell-vim-now.
--- Syncing Haskell-Vim-Now with upstream...
Current branch master is up to date.
--- Installing system packages [] using [BREW]...
--- Installing with homebrew...
This command requires a formula argument
--- Checking ctags' exuberance...
--- Setting git to use fully-pathed vim for messages...
--- Testing for broken Ruby interface in vim...
--- Test passed. Ruby interface is OK.
--- Backing up current vim config using timestamp 20161015_135753...
	/home/michael/.config/haskell-vim-now/backup/.vim.20161015_135753
	/home/michael/.config/haskell-vim-now/backup/.vimrc.20161015_135753
--- Creating vim config symlinks
	~/.vimrc -> /home/michael/.config/haskell-vim-now/.vimrc
	~/.vim   -> /home/michael/.config/haskell-vim-now/.vim
--- Installing plugins using vim-plug...
--- Setting up GHC if needed...
	Stack bin path: /home/michael/.local/bin
	Stack global path: /home/michael/.stack
	Stack global config location: /home/michael/.stack/global-project/stack.yaml
	Stack resolver: lts-7.3
	/home/michael/.config/haskell-vim-now/.stack-bin -> /home/michael/.local/bin
--- Installing helper binaries...
Plan construction failed.
*** Binary installation failed with error 1.
*** Aborting...
`

I hope we can find a fix
I'm using fedora 22

**Comment by begriffs** [comment]
OK everyone, give it another try and let me know how it goes. I merged a possible fix.

**Comment by Weznon** [comment]
It works now!
It failed the first time with

Progress: 174/175There was an error reading the package tarball /home/weznon/.stack/indices/Hackage/packages/ghc-exactprint/0.5.2.1/ghc-exactprint-0.5.2.1.tar.gz: NotTarFormat

but running it again did not get this message, I recieved a successful installation message.

Thanks a lot!

**Comment by michaellindon** [comment]
Great! Worked first time for me, thanks :)
