### ISSUE TITLE
[Allow] disabling of the concealer

### ISSUE THREAD

**Issue by AndreasPK** [begriffs/haskell-vim-now#210]
I found no way to disable replacment of /=, \, -> and <-

hsoptions is set to "q𝐒𝐓𝐄𝐌℘xe⇒⇔↱rblw-iRtBQZDC1a" which should work for the arrows but seems to be buggy.

Is there a way to disable the concealer plugin once loaded? If not maybe it's possible to allow setting of a flag in the pre-config which prevents the plugging getting loaded at all.

**Comment by begriffs** [comment]
Try the steps discussed in #159 and let me know if it works for you.

**Comment by AndreasPK** [comment]
Setting the hsoptions sadly didn't work but let g:no_haskell_conceal = 1 worked to disable it completely.
