### ISSUE TITLE
Feature Request: LambdaCase

### ISSUE THREAD

**Issue by carldong** [begriffs/haskell-vim-now#211]
Currently, LambdaCase indentation doesn't really work, while this is expected:

```
\case
  Pattern1 -> ...
  Pattern2 -> ...
```

Currently there is no auto indentation before the patterns

**Comment by begriffs** [comment]
The indentation is provided by the [haskell-vim](https://github.com/neovimhaskell/haskell-vim) plugin loaded [here](https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L117) in our vimrc.

You'll need to request this feature upstream in that plugin and once they implement it you can run `:PlugUpdate` in vim (or re-run the haskell-vim-now installer).

**Comment by begriffs** [comment]
Sound good? Shall I close this issue?

**Comment by carldong** [comment]
Yes
