### ISSUE TITLE
Cannot update because of unstaged changes.

### ISSUE THREAD

**Issue by ryanpcmcquen** [begriffs/haskell-vim-now#213]
```
--> Existing Haskell-Vim-Now installation detected at ~/.config/haskell-vim-now.
--- Syncing Haskell-Vim-Now with upstream...
error: Cannot pull with rebase: You have unstaged changes.
*** Sync (git pull) failed. Aborting...
```

I haven't made any changes to `haskell-vim-now`, so perhaps it is referring to the plugin files that have been downloaded? Maybe the `update_pull()` shell function should instead do something like this?

```
git fetch --all
git reset --hard origin/master
```

Instead of `git pull --rebase`?

https://github.com/begriffs/haskell-vim-now/blob/master/install.sh#L39-L43

**Comment by begriffs** [comment]
Just to double-check, what does `git status` say in the `~/.config/haskell-vim-now` directory?

**Comment by ryanpcmcquen** [comment]
Weirdly my `.vimrc` is empty (not just the symlink, but the file inside of `~/.config/haskell-vim-now/`). Running this fixed it:

```
git reset --hard
git pull --rebase
```

Do you see a disadvantage to changing the command to this? Or possibly giving the user an option if they want to _force_ a sync?

```
  read -p "Would you like to force a sync?  [y/N]: " response
  case $response in
    [yY][eE][sS]|[yY])
      git reset --hard
    ;;
  esac
```

**Comment by begriffs** [comment]
Sure we could do that. I'd want to be sure that the prompt makes it clear this will destroy any local changes, though.

Would you care to send a pull request for this?

**Comment by ryanpcmcquen** [comment]
Yes, I'll put it together with a nice big warning, thanks!
