### ISSUE TITLE
Installer requires 'par'!

### ISSUE THREAD

**Issue by jbolila** [begriffs/haskell-vim-now#214]
what is 'par' ?

```bash
++ not_exist+=("${prg}")
++ echo par
++ return 1
+ local NOT_INSTALLED=par
+ '[' '!' -z par ']'
+ exit_err 'Installer requires '\''par'\''. Please install and try again.'
+ err Installer requires ''\''par'\''.' Please install and try again.
+ echo -e '*** Installer' requires ''\''par'\''.' Please install and try 'again.'
*** Installer requires 'par'. Please install and try again.
+ err Aborting...
+ echo -e '*** Aborting...'
*** Aborting...
+ exit 1
```

.. can be because i'm newb to Haskell!

**Comment by begriffs** [comment]
Par (probably short for "paragraph") is a unix utility that wraps long lines of text. In haskell-vim-now when you press the standard vim reformatting key, `gq`, on a text selection in a Haskell file it runs it through `hindent`. However on a non-Haskell file it sends the selection through `par`.

**Comment by markbook2** [comment]
Here is an official page http://www.nicemice.net/par/. It is available in AUR for Arch Linux - https://aur.archlinux.org/packages/par/.

**Comment by tag-them** [comment]
The official page is unavailable atm. Still managed to install it via AUR by setting the source to [its archive.org entry](https://web.archive.org/web/20161217225116/www.nicemice.net/par/Par152.tar.gz)
