### ISSUE TITLE
Consider adding vim-bracketed-paste to fix issues when pasting while in Insert mode.

### ISSUE THREAD

**Issue by ryanpcmcquen** [begriffs/haskell-vim-now#218]
Before using `haskell-vim-now`, I used Vim for several years without any plugins ... except one that I would always put inside of my `.vimrc`. That plugin was [vim-bracketed-paste](https://github.com/ConradIrwin/vim-bracketed-paste). Would you consider adding it to `haskell-vim-now`? If so, I can easily put together a pull request.

I made some videos showing the difference between pasting without the plugin:
https://app.hyfy.io/v/abqG8jKEq0/

And with the plugin:
https://app.hyfy.io/v/abyM5IIMq0/

Moral of the story is that Vim completely garbles the indentation if you paste while in Insert mode.

**Comment by begriffs** [comment]
Haskell-vim-now currently maps `,p` to do this kind of paste, but having it automatically detect an OS-level paste sounds more convenient. Please do send a pull request!
