### ISSUE TITLE
hindent 4 is installed but vim config uses hindent 5 command line options

### ISSUE THREAD

**Issue by jship** [begriffs/haskell-vim-now#221]
Running the `haskell-vim-now` installer fresh results in `hindent` 4.6.4 (see https://www.stackage.org/lts-7.14/package/hindent-4.6.4), but the command line options used for the `gq` format selection command are for `hindent` 5.x.x.

Should temporarily pin `hindent` to 5.x.x.  Latest at this time is 5.2.1.  Pull request coming soon.

**Comment by begriffs** [comment]
Thanks for the report and your help.
