### ISSUE TITLE
Consider `softtabstop`?

### ISSUE THREAD

**Issue by ryanpcmcquen** [begriffs/haskell-vim-now#223]
`haskell-vim-now` currently sets `tabstop=2` rather than `softtabstop=2`. The main difference here is that `softtabstop` will always insert `2` spaces (even in a file that currently has tabs).

Perhaps this is the desired behavior, but I had not noticed any discussion about it in previous issues. Another difference is that using `softtabstop=2` would show tabs as taking `8` spaces rather than `2` spaces (in files with real tabs).

**Comment by begriffs** [comment]
Sure that sounds good. Happy to make it work better for people who use tabs. Want to send a pull request?

**Comment by ryanpcmcquen** [comment]
Is it better for tab users if we keep tabs in files that already have tabs (`tabstop`), or insist on 2 spaces no matter what (`softtabstop`)? I guess I'm on the fence. :smile_cat:

**Comment by ryanpcmcquen** [comment]
OK, I think using `softtabstop` is more consistent, but it would also be nice if we mapped <kbd>Shift</kbd> + <kbd>Tab</kbd> to insert an actual tab character:

```
inoremap <S-Tab> <C-V><Tab>
```

Where would that fit best in the file? Perhaps, [here](https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L403-L404)?

**Comment by ryanpcmcquen** [comment]
Is there another mapping that would be less confusing? Or should we just avoid all mappings?

**Comment by ryanpcmcquen** [comment]
FYI, in standard Vim, <kbd>Ctrl</kbd> + <kbd>T</kbd> inserts a Tab character.
