### ISSUE TITLE
Can't get alternate color scheme to work correctly

### ISSUE THREAD

**Issue by Tientuine** [begriffs/haskell-vim-now#229]
After installing haskell-vim-now, one of the first changes I wanted to make was to switch to the solarized color scheme. I installed this color scheme in the bundle folder per the instructions at https://github.com/altercation/vim-colors-solarized, exactly as I have done in the past before trying haskell-vim-now.

I edited my .vimrc to comment out the wombat color scheme and added instead the line `colorscheme solarized`. However, when launching vim, the colors do not appear to be correct. I don't know if this is an issue with other settings in the .vimrc or the plug script or something else, but I'm currently stumped. Images are attached for comparison.

Has anyone else gotten the solarized color scheme to work correctly with the haskell-vim-now setup? And, if so, what steps did you follow (i.e., what am I missing)?

Preemptive thanks to any respondents.

P.S. I also tried adding the line `Plug 'vim-scripts/solarized.vim'` in the vim-plug section right under the corresponding line for wombat, and the result was the same.

Under haskell-vim-now (Bad!):
![solarizedbad](https://cloud.githubusercontent.com/assets/1669148/22855415/3dbaf5b8-f04e-11e6-96d3-e6bde597569e.png)
Under both vanilla and haskell-vim-proto (Good!):
![solarizedgood](https://cloud.githubusercontent.com/assets/1669148/22855414/3db992fe-f04e-11e6-9be1-02302114076f.png)

**Comment by begriffs** [comment]
Try this:

1. Undo your changes to the main vimrc, it is under version control.
2. Add the plugin to `~/.config/haskell-vim-now/plugins.vim`
   ```viml
   Plug 'altercation/vim-colors-solarized'
   ```
3. Restart vim and run `:PlugInstall`
4. Add your customization to `~/.config/haskell-vim-now/vimrc.local`:
   ```vml
   set background=dark
   let g:solarized_termcolors=256
   colorscheme solarized
   ```
5. Restart vim (or `:so $MYVIMRC`)

**Comment by Tientuine** [comment]
Thanks, this worked great without `solarized_termcolors=256` (I like the traditional dark turquoise background, rather than the black/charcoal that I seem to get with that setting). Neither file you mentioned, plugins.vim nor vimrc.local, already existed so I simply created them. I appreciate the help.

**Comment by Tientuine** [comment]
Okay, sorry to re-open this, but I noticed that the Status Line color scheme has not changed. Is there an easy way to change that to match the main and command buffers?

**Comment by begriffs** [comment]
Looks like the base vim-airline package has moved on github. I pushed a change to master and you'll need it I think. Just run the haskell-vim-now installer again and it will update for you.

Then add `Plug 'vim-airline/vim-airline-themes'` to plugins.vim, and set

```viml
let g:airline_theme='base16_solarized'
```
in vimrc.local

**Comment by Tientuine** [comment]
Worked like a charm. Thanks, again.
