### ISSUE TITLE
stack resolver >= 8 build fail on `Binary installation failed with error`

### ISSUE THREAD

**Issue by wizzup** [begriffs/haskell-vim-now#233]
I have resolver=8.3 in `~/.stack/global-project/stack.yaml` and running `bash haskell-vim-now.sh` failed with error `Binary installation failed with error -1`

Change resolver to 7.19 do solve the problem

Suspect cause [setup.sh](https://github.com/begriffs/haskell-vim-now/blob/27c53976469bf4edd35efbd0d916e47613ac15f1/scripts/setup.sh#L59)

**Comment by tsoernes** [comment]
+1

**Comment by ymg** [comment]
Getting same error with 8.0.2 as well, any idea what dependency is causing this?

**Comment by begriffs** [comment]
Looks similar to #231

@wizzup can you try running the installer again and including any error messages you see in the output?

**Comment by ymg** [comment]
@begriffs this works brilliantly, thank you so much 👍

**Comment by wizzup** [comment]
This is the same as #231
