### ISSUE TITLE
Compiler or linter not working when in project

### ISSUE THREAD

**Issue by tsoernes** [begriffs/haskell-vim-now#236]
If I use VIM on a standalone .hs file, everything works as expected.  Now I did `stack new` and made a hello-world program. `,hl` or `,hc` no longer working for the .hs files inside the project. 

`stack build` has no errors
`stack exec --no-ghc-package-path  -- cabal build` has no errors. 
Loading the project into `stack repl` works. I tried rebooting, as was suggested in a similar issue without success. I also tried running the `haskell-vim-now.sh` file again. It reports no errors.

**Comment by begriffs** [comment]
I believe this happens when the cabal version used in a project differs from the cabal version used to build ghc-mod. The best way I've found to deal with this is to build ghc-mod using the same stack LTS version of your project, and then add a symlink from ~/.local/bin/ghc-mod -> the location of the binary your built.

Either that or have the project resolver match the global stack resolver.

**Comment by tsoernes** [comment]
```
stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1

ghc-mod --version
ghc-mod version 5.6.0.0 compiled by GHC 8.0.1
```
Then I changed project stack.yaml to: 
```
resolver: ghc-8.0.1
```
Then I did stack build in project directory, but no luck. Any tips?

**Comment by tsoernes** [comment]
I found the issue; and the solution.

ghc-mod and the like, is called through Stack. Stack can only work on files that you own. Perhaps there's some way to add `--allow-different-user` as a default option for Stack in Haskell Vim? If not, then try to `chown` the file. If that doesn't work, which was my case, the NTFS drive containing the file needs to be remounted with user, not root permissions.  Here's the line from my /etc/fstab for the disk containing the file:

`UUID=1C6C888C6C88627E 				/mnt/128GB	ntfs rw,auto,users,noatime,nosuid,nodev,nofail,x-gvfs-show,fmask=0000,dmask=0000,exec,permissions,uid=1000,gid=1000		0 2`

**Comment by begriffs** [comment]
@tsoernes, good debugging work! Maybe you should open an issue upstream at https://github.com/eagletmt/ghcmod-vim which is the plugin that is responsible for calling ghc-mod. That way they can fix it not just for haskell-vim-now but for any vim ghc-mod user.
