### ISSUE TITLE
How to use easymotion?

### ISSUE THREAD

**Issue by suzumiyasmith** [begriffs/haskell-vim-now#240]
Sorry for my naive question.
I check `:map` but cannot find key binding for <Leader><Leader> in `easymotion`.
And I wanna ask how to jump to next error.
Thanks for your patience for a fresher.

**Comment by tdfirth** [comment]
If you haven't figured this out by now, double tap the leader key (which is , if you haven't changed it).  Then press the movement key in the direction you want to move.  E.g., ,,j will open up all of your options to move down or ,,w will open up your options to jump forward by the start of words.

**Comment by suzumiyasmith** [comment]
Really thank you. I stuck on which key is `<leader>` for such a long time. Thanks for your attention for a vim newb again. :D
