### ISSUE TITLE
,y yank 

### ISSUE THREAD

**Issue by arbitary** [begriffs/haskell-vim-now#242]
I am using Mac. `,y` doesn't work for me. I can't copy to the system's clipboard. Am I missing an option in my vim setup?

**Comment by melkor217** [comment]
ehm, http://vim.wikia.com/wiki/Mac_OS_X_clipboard_sharing

**Comment by begriffs** [comment]
Maybe we ought to add `set clipboard=unnamed` to the vimrc? It's weird, I've been able to use `,y` fine on my mac...

**Comment by arbitary** [comment]
It's working now after I installed vim using homebrew; I was using the vim preinstalled on Sierra. Thanks guys.
