### ISSUE TITLE
hsConcealPlus not properly showing

### ISSUE THREAD

**Issue by ymg** [begriffs/haskell-vim-now#245]
Hello,

What would be the issue causing this? Is there anyway I can do a clean install to get rid of all of this? Notice even the type arrows are dark (you can see them when you move the cursor to that particular line)

<img width="1440" alt="screen shot 2017-05-03 at 4 24 58 pm" src="https://cloud.githubusercontent.com/assets/2401097/25667997/3b598b22-301d-11e7-8c6a-712eed4a53a9.png">

**Comment by begriffs** [comment]
What is your terminal font? Maybe it cannot support those unicode characters.

**Comment by ymg** [comment]
It's set to Monaco 12pt, I've also installed the Powerline fonts if that helps debugging

**Comment by ymg** [comment]
Nevermind, I've noticed that the second non-ASCII font is set to Monaco so that's why it keeps screwing up the ligatures :(

Thanks a lot for the prompt response though!
