### ISSUE TITLE
error when generate tags

### ISSUE THREAD

**Issue by fill32** [begriffs/haskell-vim-now#260]
I got this error when trying to build tags: ,tg

codex: Run the 'configure' command first.
codex: *warning* falling back on dependency resolution using hackage
codex: No cabal file found.
CallStack (from HasCallStack):
  error, called at src/Codex/Project.hs:65:16 in codex-0.5.1.2-2sevYNN39I9LUjjRC8Vu6v:Codex.Project

vim 8.0, osx 10.12.5

**Comment by jship** [comment]
Did you install haskell-vim-now recently (past week) or is it an older install?

**Comment by fill32** [comment]
Just install today :D

**Comment by fill32** [comment]
Oh my bad, my working directory just has only *.hs files, maybe that's why the `codex`  tool can't run correctly. If I create a new project with `stack new`, then `codex` can run without errors.

**Comment by fill32** [comment]
And I have to add create git repo, add files to be able to use `git-hscope` 😂
