### ISSUE TITLE
Trouble getting powerline font support installed properly.

### ISSUE THREAD

**Issue by capn-freako** [begriffs/haskell-vim-now#263]
I love the pretty printing on non-active lines!
However, I think I must have not quite gotten the _powerline_ font support instructions interpreted correctly, because I'm getting boxed question marks in place of the following source code elements:

- =>
- ++
- fmap

as well as scattered about in the non-content portions of my _MacVim_ window.

I did find the instructions, here:
[Powerline fonts installation instructions](https://powerline.readthedocs.io/en/master/installation.html#fonts-installation)
a bit confusing, although I did get through them error-free.

I did notice, when I'd finished, that the _Terminess for Powerline_ font didn't show up in my _Font Book_, even though I followed the hints intended to prevent this:

```
Davids-Air-2:fonts dbanas$ cp fontconfig/50-enable-terminess-powerline.conf ~/.config/fontconfig/conf.d/
Davids-Air-2:fonts dbanas$ fc-cache -vf
/usr/share/fonts: skipping, no such directory
/System/Library/Fonts: caching, new cache contents: 281 fonts, 0 dirs
{snip}
fc-cache: succeeded
```

and they ran without error.

**Comment by capn-freako** [comment]
Okay, I just found my way to this repository:
https://github.com/enomsg/vim-haskellConcealPlus#available-options

And, near the bottom of the _ReadMe_:

> Finding proper fonts might be a pain. Most of modern, so called programming fonts (Inconsolata, Anonymous Pro, etc.) often lack decent unicode support. As a recommendation, try DejaVu Sans Mono.


I changed my MacVim font to _DejaVu Sans Mono for Powerline_ and, Voila', no more boxed question marks anywhere in my MacVim window; Yeah!

I'm curious: why is _Monaco_ set as the default font for new **haskell-vim-now** installations, given that it is _not_ included in the set of fonts patched for _Powerline_?

**Comment by begriffs** [comment]
I don't remember why the font is set that way. I think I might have patched Monaco once upon a time on my machine and then forgot about it. Want to send a PR to change the default to something that will work better for other people?

**Comment by begriffs** [comment]
(ping)

**Comment by sjking** [comment]
Setting a Powerline font in `~/.gvimrc` was my solution:
```
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h15
```
I'm not sure if this should simply be documented, or part of the build because it first requires installing the Powerline fonts.
