### ISSUE TITLE
Parallel Install to keep my normal vim for everything else?

### ISSUE THREAD

**Issue by jonahx** [begriffs/haskell-vim-now#271]
This project seems great, but I use vim for nearly everything, and can't afford to have my normal config blown away.

Is there a way to install this such that I can open vim in "haskell-vim-now" mode when I'm writing haskell, but keep normal vim for everything else?  I don't mind having to open vim with special flags at the command line to achieve this.

Thanks.

**Comment by begriffs** [comment]
I admit that this project is pretty opinionated and takes over the vim config. One thing you can do is add your own configuration to `~/.config/haskell-vim-now/vimrc.local` which gets loaded after the default project settings. That will allow you to override settings with your own preferences. Also you can install your own choice of plugins in `~/.config/haskell-vim-now/plugins.vim`. (There's a [section](https://github.com/begriffs/haskell-vim-now#customizing) in the readme about customization.)

Do you think this is what you need, or are you desiring something more?

**Comment by jonahx** [comment]
Thanks for the reply.

I am desiring something more -- or perhaps less.  What I want to do may be better answered as a pure vim question, in that I want the ability to have, essentially, 2 vim installs (or 2 entire configs, with their own vimrc, plugins, etc).  1 would be "haskell-vim-now" and 1 would be exactly what my personal vim is now.

**Comment by begriffs** [comment]
You could do it with a symlink, which is how haskell-vim-now works:

```
.vimrc -> /Users/j/.config/haskell-vim-now/.vimrc
.vim -> /Users/j/.config/haskell-vim-now/.vim
```

Just point them at your config instead when you want. Could create mvim (aka "my vim") as a shell script that does that.

**Comment by jonahx** [comment]
And then you would set the plugin directories inside the different `.vimrc`s...

Ok, I can probably figure something out.  Thanks.

**Comment by begriffs** [comment]
Cool. I'll close this issue. Feel free to comment if you run into any problems along the way with this approach.

**Comment by bjornbm** [comment]
Also feel free to comment with exactly what you did @jonahx to make it work for you. Could be useful for others. :)
