### ISSUE TITLE
Install error, now I can't open vim. Help!

### ISSUE THREAD

**Issue by pirey** [begriffs/haskell-vim-now#277]
Hi, I made some mistake when installing. I use mac osx el capitan.

so I just basically run the install command from README, and notice some error and managed to get rid of it, includes
- upgrades homebrew version from ? to 1.3.8 (I can't remember previous version)
- upgrade ruby version, from 2.3 to 2.4
- running xcode-select --install

what I didn't realize is, the install command uses `bash /tmp/haskell-vim-now.sh` while I'm using zsh. So it seems to me that the install script is installing the wrong stuff but I have no idea what it is.

the problem now is after I realize that I'm using zsh and re-run the install command using `zsh /tmp/haskell-vim-now.sh` I get the following error

![image](https://user-images.githubusercontent.com/10344542/33539372-b28862b6-d8f8-11e7-929e-75b0772b2c1b.png)

And now I can't open vim!!!!
Whenever I try to open vim, I get this error 
![image](https://user-images.githubusercontent.com/10344542/33539417-d8823406-d8f8-11e7-8724-b2a9a75076f0.png)

Thanks for your help!

**Comment by begriffs** [comment]
We can look into the installation problem later, but to solve your vim not starting problem you can restore your old configuration files. The haskell-vim-now installer has [backed them up](https://github.com/begriffs/haskell-vim-now/blob/master/scripts/setup.sh#L92) for you.

Look in your `~/.config/haskell-vim-now/backup` directory. Get rid of the `.vimrc` and `.vim` symlinks in your home directory and copy these files from this backup directory to your home.

**Comment by pirey** [comment]
I just upgraded vim via homebrew and somehow its working now.
thank you.
