### ISSUE TITLE
Interested in fzf?

### ISSUE THREAD

**Issue by jship** [begriffs/haskell-vim-now#281]
A coworker got me hooked on [`fzf`](https://github.com/junegunn/fzf.vim).  Interested in a PR to replace `ctrl+p` with `fzf`?

Another nice bit:  `fzf` can use [`ripgrep`](https://github.com/BurntSushi/ripgrep) as the backing search tool for searching the contents of files and it is super fast.  I've been exclusively using `ripgrep`-powered `fzf` for code searching recently.

**Comment by begriffs** [comment]
If we can keep the searching interface the same but it will go faster then yeah let's try it!
