### ISSUE TITLE
Create local hoogle db for current project

### ISSUE THREAD

**Issue by begriffs** [begriffs/haskell-vim-now#29]
Using https://github.com/gilligan/hoobuddy

It will make the search results relevant to the project.

**Comment by DylanLukes** [comment]
Is there any progress on this? It'd be nice to at least have Hoogle prioritize local dependencies... but it'd be even better if Hoogle would search locally installed packages and documentation.

Maybe there's a way to do this I'm not aware of?

**Comment by begriffs** [comment]
Oh actually I recorded the issue just to remind myself for later. Haven't taken a look at it yet.

One thing you can do which may be helpful is jump to the definition of a word under the cursor with `CTRL-]`. The tag system knows about the symbols everywhere inside your cabal sandbox.

I'd very much welcome a pull request about this, even if it's a work in progress. I'm pretty busy for the next few weeks (new job and other open source maintenance) so any help is appreciated.

**Comment by begriffs** [comment]
Closing this issue so we can discuss the new way to use hoogle in issue #154
