### ISSUE TITLE
Stalling on installing Hackage...

### ISSUE THREAD

**Issue by peterstorm** [begriffs/haskell-vim-now#290]
I can't seem to update the package index in Hackage when using Amazon... it just hangs. If I go to the mirrored link, it just says access denied.

I manually installed Hackage using a different mirror, from stack, but the install script from vim-now isn't finishing, because of the hang, so I don't know how to move on?

**Comment by begriffs** [comment]
How did you end up resolving the issue?

**Comment by peterstorm** [comment]
It just worked in the end actually, after retrying a couple of times :) But I can't get hoogle, or ghc-mod or anything else to work really, so I'm trying a complete reinstall.
