### ISSUE TITLE
:Align = aligns weiiiird?

### ISSUE THREAD

**Issue by peterstorm** [begriffs/haskell-vim-now#292]
I have this code:
```
mult1 = x * y
where x = 5
y = 6
```
and `:Align =` refactors that to
```
mult1     = x * y
where x = 5
y            = 6
```
which is not valid haskell :( Is there any better alternative?

**Comment by peterstorm** [comment]
Ok, the last example is actually aligned on the equal signs, but shouldn't it push the `y` out to the equal sign?

**Comment by begriffs** [comment]
I think Align doesn't know about Haskell, it just manipulates plain text.

For Haskell code formatting, try selection a region and pressing `gq`, which spawns hindent. Not sure if it will align equal signs though.

**Comment by peterstorm** [comment]
Oh, damn :(

Isn't there some way I could write code to lint, so everything aligned on equal signs, but still stayed with connected to the signs, and didn't get unnested?
