### ISSUE TITLE
Which file or line of code is responaible for creating the syntax?

### ISSUE THREAD

**Issue by peterstorm** [begriffs/haskell-vim-now#294]
So, weird noob question.

When I just write Haskell code, which file or line of code is responsible for indenting where clauses and guards, for example?

**Comment by begriffs** [comment]
This one IIRC: https://github.com/begriffs/haskell-vim-now/blob/baf3c8c979a98a9595b0a6f819e1b253c7e90ef1/.vimrc#L118
