### ISSUE TITLE
Nested allignments

### ISSUE THREAD

**Issue by DeadDork** [begriffs/haskell-vim-now#37]
I love HVN's align feature. It certainly makes my life a little easier! That being said, I frequently align lines internally, too. E.G. the `=` below:

```Haskell
fib n | n ≡ 0        = 0
      | n ≡ 1        = 1
      | otherwise    = fib (n - 1) + fib (n - 2)
```

It doesn't look like there is a way to do that with HVN as of yet. Is this something that's doable?

Thanks!

P.S. GitHub is aligning things weird, so the space numbers above don't actually match up. The above does capture what I'm going for visually, though.

**Comment by begriffs** [comment]
You could try visually selecting a region (with capital V) then run `,a=` to align equal signs. Does this do what you'd like?

**Comment by begriffs** [comment]
Did you figure this out? Should I close the issue?
