### ISSUE TITLE
'Show expression type under cursor' works, but ,hT inserts a blank line above

### ISSUE THREAD

**Issue by Decoherence** [begriffs/haskell-vim-now#44]
When editing a Haskell file, `,ht` reports the correct expression type under the cursor. But when I try to insert the type using `,hT`, a blank line is inserted instead of the expression type. 

Interestingly, `,hT` works correctly for the `main` function--correctly inserting `main :: IO ()`. But `,hT` inserts a blank line for all other functions in a file. 

I tried `,hT` within a sandbox as well, but had the same issue. Perhaps I'm missing something simple. Any pointers would be appreciated! 

Using latest haskell-vim-now on Yosemite, GHC 7.8.3, ghc-mod 5.2.1.2 compiled by GHC  7.8.3, vim 7.4/MacVim 73.

P.S. Thanks for your efforts in creating/maintaining this awesome Haskell paradise! :thumbsup:

**Comment by begriffs** [comment]
I haven't had problems locally, but i'm on ghc-mod 4.1.6. Can you share a link to the file you're editing so I can try it in my configuration?

**Comment by Decoherence** [comment]
Thanks for the quick reply! I found the issue. After doing a clean install of GHC 7.8.4 and removing `haskell-vim-now`, I re-ran the install script. 

That's when I noticed the cabal install error for `haskell-src-exts` due to `happy` not being found. After installing `happy` and running the install script again, everything works as expected. 

I see this is already noted on the Wiki page--so I should have realized the issue sooner. Perhaps there's a way for the install script to detect this scenario. Or just a note on the home page. I'm guessing anyone doing a clean install will encounter this issue, especially those new to the joys of cabal :-). 

For reference, my now working installation is using GHC 7.8.4 for OS X as provided on the new `haskell.org` page. This can be closed now.

**Comment by begriffs** [comment]
Glad you found the solution. Do you know a way to detect if happy is installed on a system? I could add that check to the pre-install checks in my script.

**Comment by begriffs** [comment]
If you run `which happy` in your shell, does it find an executable? It does on my computer so I may be able to check for its presence that way.

**Comment by Decoherence** [comment]
That should work. 

The OS X GHC 7.8.4 installation utility from `haskell.org` updates the user's $PATH. It does so by appending the following to `~/.bash_profile`: 

# Add GHC 7.8.4 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/ghc-7.8.4.app"
if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi

So if the user has installed `happy`, running `which happy` would return: 
`~/.cabal/bin/happy`

![screen shot 2015-02-22 at 1 50 10 pm](https://cloud.githubusercontent.com/assets/3780824/6319837/c29bbcfa-ba99-11e4-9c37-a6702713b4c0.png)
