### ISSUE TITLE
Replace 'jk' with something better

### ISSUE THREAD

**Issue by Ancipital** [begriffs/haskell-vim-now#45]
In Dutch, 'jk' are letters that used quite often in normal messages, in fact, my surname ends with those letters. Thus maybe 'jk' to exit from insert mode could be replaced with something better, 'jjk' for example.

**Comment by begriffs** [comment]
Thanks for pointing this out.

For now I'll simply remove the `jk` binding. The person who submitted it as a pull request can override it in their `vimrc.local`.
