### ISSUE TITLE
Installable on Win8?

### ISSUE THREAD

**Issue by TimoFreiberg** [begriffs/haskell-vim-now#47]
I assume not, I tried installing the missing tools anyway and got stuck trying to install curl-config on Windows.
Any recommendations for Windows users?

**Comment by Enamex** [comment]
Yes please. I was so excited for the possibility of a good, easy-to-install Haskell IDE that discovering this's a non-Windows deal, well, it felt bad.

**Comment by begriffs** [comment]
I think it checks for curl-config as a way to see if the system has libcurl installed. Try running the windows installer for curl and see if the error goes away. http://curl.haxx.se/download.html

**Comment by begriffs** [comment]
@TimoFreiberg, any luck installing on windows? Did the curl thing help?

**Comment by TimoFreiberg** [comment]
I didn't get it to run under native Windows. A little while ago, I started using [babun](http://babun.github.io/) (which is a cygwin/zsh config), which included libcurl. The installation didn't run properly anyway, though.
I didn't keep the logs though, I'll try it again when I'm on a windows machine.

**Comment by begriffs** [comment]
Thanks, let me know what the logs say. I'd like to make it installable on windows if possible.

**Comment by TimoFreiberg** [comment]
I was about to properly document everything and try and fix small issues in the script myself, but I somehow broke cabal inside cygwin. It may take a while

**Comment by begriffs** [comment]
Oh man that's no fun. Sometimes it's smoothest to just erase GHC and Cabal and reinstall. What error are you getting from Cabal? I might be able to help diagnose the problem.

**Comment by TimoFreiberg** [comment]
This: https://github.com/haskell/cabal/issues/2049
Couldn't update cabal either, reinstalling now.
One thing that doesn't work on Cygwin is the line
```bash
sb=`mktemp -d /${TMPDIR:-/tmp}/build-XXXX`
```
, which returns
```
mktemp: failed to create directory via template ‘//tmp/build-XXXX’: No such file or directory
```
Sorry for the slow feedback!

**Comment by begriffs** [comment]
I adjusted the paths for `mktemp`. Let me know how it works now.

**Comment by TimoFreiberg** [comment]
Tried it again today, main error seems to be related to path expansion again:
```
setup-Simple-Cabal-1.22.2.0-i386-windows-ghc-7.10.1.exe: 'D:\Program
Files\minghc-7.10.1-i386\ghc-7.10.1\bin\ghc-pkg.exe' exited with an error:
data-default-class-0.0.1: haddock-interfaces:
/home/ara/.haskell-vim-now/data\doc\i386-windows-ghc-7.10.1\data-default-class-0.0.1\html\data-default-class.haddock
is a relative path which makes no sense (as there is nothing for it to be
relative to). You can make paths relative to the package database itself by
using ${pkgroot}. (use --force to override)
```
[Full output here](https://gist.github.com/TimoFreiberg/3a4a0d41d869c30aa992).
I'm going to try and move ghc to the cygwin file system, maybe that will work.

**Comment by begriffs** [comment]
@TimoFreiberg I think things would work better in windows now. If you install [Stack for windows](https://github.com/commercialhaskell/stack/blob/release/doc/install_and_upgrade.md#windows) and then run the haskell-vim-now installer again it may just work.

**Comment by begriffs** [comment]
Since there has been no reply to this issue I am closing it.

**Comment by miladz68** [comment]
I have the same issue on windows 7. When I run the bash script as said in the installation guide I get the error : 
```
*** Installer requires 'curl-config ctags make par '. Please install and try again.
*** Aborting...
```

 I managed to install make, par, curl and ctags, but I couldn't install curl-config. I couldn't find any curl-config executable anywhere on the net and I couldn't build it from the source. 

It seems that one way install it is via cygwin, which I am not familiar with.

**Comment by jship** [comment]
@miladz68: Are you installing via git bash?

**Comment by miladz68** [comment]
@jship No, must I install through git bash ?

**Comment by jship** [comment]
miladz68: No, git bash is not required.  What shell are you using to run the install script on Windows?

I'm curious because we've had some discussion over on #249 about rewriting the installer in a language other than bash to better support Windows.

If there is some way we can update the scripts, maybe a powershell wrapper that `choco install`s the deps, it could be a much more "low hanging fruit" option to support Windows than what is proposed in #249.

**Comment by miladz68** [comment]
@jship  I have tested it with cmder and git-bash, both fail with the same message.

**Comment by jship** [comment]
@miladz68: Does cmder provide a bash shell?

**Comment by miladz68** [comment]
@jship  I can run `bash /tmp/haskell-vim-now.sh` and it runs OK and gives me an error message. also some unix commands like ls work in it. So I guess the answer is yes.

**Comment by jship** [comment]
@miladz68: Thanks.  That gives me some food for thought.
