### ISSUE TITLE
Error of haskell-src-exts-1.16.0.1 during installation 

### ISSUE THREAD

**Issue by edyu** [begriffs/haskell-vim-now#48]
https://gist.github.com/edyu/8ab572e5ae9b42b6ee11

**Comment by edyu** [comment]
Configuring haskell-src-exts-1.16.0.1...
setup-Simple-Cabal-1.18.1.5-x86_64-osx-ghc-7.8.4: The program happy version >=1.17 is required but it could not be found.
cabal: Error: some packages failed to install:
ghc-mod-4.1.6 depends on haskell-src-exts-1.16.0.1 which failed to install.
haskell-src-exts-1.16.0.1 failed during the configure step. The exception was:
ExitFailure 1
hlint-1.9.18 depends on haskell-src-exts-1.16.0.1 which failed to install.

**Comment by begriffs** [comment]
If you run `which happy` what does it say? I think I may just have to add a check in the installer that happy exists.

**Comment by edyu** [comment]
which happy
happy not found

**Comment by edyu** [comment]
I'm running cabal install happy manually now.

**Comment by begriffs** [comment]
After installing Happy did the rest of the install go OK?

**Comment by edyu** [comment]
Joe,
  Sorry, I didn't get to it until late last night and the installation took a long time. Yes, after installing Happy, the install went OK. Maybe check whether ~/.cabal/bin/happy exists before going forward. Thanks.

**Comment by begriffs** [comment]
Cool. I added the happy check to the installer. Thanks again for reporting the problem, I wouldn't have been able to discover it myself.

**Comment by scottdeuser** [comment]
I ran into same issue just now. I installed happy manually as suggested by @edyu 
Re-ran ```cabal install ghc-mod``` and it installed successfully. 
Ran ```cabal update``` just before starting. Any reason why @begriffs change would not have been picked up?

**Comment by lblackburn** [comment]
Is there a reason happy isn't a dependency for that cabal? Definitely tripped me up a bit.
