### ISSUE TITLE
Overeager unicode symbol replacement

### ISSUE THREAD

**Issue by begriffs** [begriffs/haskell-vim-now#55]
I'm noticing that more and more symbols are being replaced by cute characters. Now even Text and Bool are being replaced by T and B. Feels a little too cute to me and I'm considering disabling some of this.

**Comment by levinotik** [comment]
:+1: 

Came here to see if this was already an issue. I'm pretty new to haskell and I find myself going to the lines where unicode symbols have been placed just so I can see what's actually going on. It'd be nice to have a way to simply disable the character replacement.

**Comment by begriffs** [comment]
Try this update and let me know if it is still concealing too much. We can adjust it.

**Comment by levinotik** [comment]
thanks @begriffs Should I just run the curl command again over my existing install?

**Comment by begriffs** [comment]
Yep, re-running the installer does an update.

(Note that if you have modified `~/.vimrc` you should move your changes into `~/.vimrc.local` so they persist between updates)

**Comment by levinotik** [comment]
thanks

**Comment by levinotik** [comment]
Oy. I did something wrong here. I ran `cp .vimrc .vimrc.local` and ran the install. Firing up vim shows me a lot of errors :(

![screen shot 2015-06-22 at 6 54 29 pm](https://cloud.githubusercontent.com/assets/514174/8295188/441a669e-1910-11e5-9858-70ea177c00cd.png)

**Comment by levinotik** [comment]
Tried again with `mv .vimrc .vimrc.local`. Saw a message about stashing or committing changes to `.vimrc` and then the install finished, but same errors now.

**Comment by begriffs** [comment]
Hmm, here's how I'd approach it

```bash
cd
mv .vimrc.local .vimrc.backup
rm .vimrc
cd .haskell-vim-now
git reset
git checkout .
curl -o - https://raw.githubusercontent.com/begriffs/haskell-vim-now/master/install.sh | bash
```

Then selectively pull pieces out of `.vimrc.backup` into `.vimrc.local`. Try not to duplicate the things in `.vimrc`, just keep your additions.

Let me know how this works for you.

**Comment by levinotik** [comment]
Sorry for bugging you about this again, but I'm going to be running this again after cleaning out a bunch of bash cruft and wanted to clarify. Is the installer aware of my `.vimrc.local` or is the idea that I'd have to manually add back my changes to the new `.vimrc`? Thanks again.

**Comment by begriffs** [comment]
The installer does not know about your `.vimrc.local`. I was worried though that the `cp .vimrc .vimrc.local` you ran previously would put way too many things into `.vimrc.local`. You really only want to put your own overrides in there, not duplicate the entire `.vimrc` which is actually a symlink to `~/.haskell-vim-now/.vimrc` and is managed by the haskell-vim-now installer.

**Comment by ivanperez-keera** [comment]
Sorry for commenting on a closed issue, but the amount of concealing is, IMHO, too much. The following may be a much better default for those who are used to "text-based haskell". (Bonus: indentation never changes.)
```
let hscoptions="𝐒𝐓𝐄𝐌xRtB𝔻w℘xe⇔⇒rbl↱-iQ1a"
```

**Comment by begriffs** [comment]
Nice. The concealer becomes more aggressive, concealing more symbols as time goes on so it's good to fight back. Want to send this little change as a PR? I can apply it myself but I'd like to have you recognized for the commit.

**Comment by ivanperez-keera** [comment]
Sure, I'll do that. Thanks!
