### ISSUE TITLE
Installation fails when using GHC 7.10

### ISSUE THREAD

**Issue by m0davis** [begriffs/haskell-vim-now#56]
Presumably, to fix it: use https://beta.stackage.org/nightly/cabal.config when 7.10 is detected. The lts version is only for GHC 7.8, as described at https://beta.stackage.org/.

**Comment by begriffs** [comment]
Thanks for reporting, let me know if it works for you now.

**Comment by m0davis** [comment]
Unfortunately, ghc-mod fails to compile (not your fault). I've found it necessary to git clone https://github.com/kazu-yamamoto/ghc-mod.git, modify the Version in ghc-mod.cabal from 0 to 5.2.1 (for ghcmod-vim), and then cabal install. HScope is also having problems building (again, not your fault).

**Comment by begriffs** [comment]
What does the build error say? We could modify the current stackage nightly `cabal.config` until it works, then host that config in this repo and curl it down instead of using stackage.

**Comment by m0davis** [comment]
Here's the build error:

[ 6 of 38] Compiling Language.Haskell.GhcMod.Error ( Language/Haskell/GhcMod/Error.hs, dist/dist-sandbox-f709c186/build/Language/Haskell/GhcMod/Error.o )
...snip some warnings...
Language/Haskell/GhcMod/Gap.hs:256:18:
    Not in scope: data constructor ‘ExposePackageId’
    Perhaps you meant ‘ExposePackage’ (imported from DynFlags)
cabal: Error: some packages failed to install:
ghc-mod-5.2.1.2 failed during the building phase. The exception was:
ExitFailure 1

**Comment by begriffs** [comment]
Try again. I found when I manually curl'd https://beta.stackage.org/nightly/cabal.config that the result was blank because curl didn't follow the 303 redirect. Adding `-L` may properly retrieve the cabal config file.

**Comment by m0davis** [comment]
It still errors. I notice that ghc-mod is not listed in the stackage/nightly. Here's the error:

[ 9 of 38] Compiling Language.Haskell.GhcMod.Gap ( Language/Haskell/GhcMod/Gap.hs, dist/dist-sandbox-232133af/build/Language/Haskell/GhcMod/Gap.o )

Language/Haskell/GhcMod/Gap.hs:256:18:
    Not in scope: data constructor ‘ExposePackageId’
    Perhaps you meant ‘ExposePackage’ (imported from DynFlags)

**Comment by begriffs** [comment]
Looks like a more general problem with ghc-mod and 7.10: https://github.com/kazu-yamamoto/ghc-mod/issues/437

**Comment by m0davis** [comment]
Yup.
