### ISSUE TITLE
Having some problems getting things to work

### ISSUE THREAD

**Issue by favetelinguis** [begriffs/haskell-vim-now#58]
Im using Mac OSX 10.9.5
Vim 7.4.

The commands I'm having problem with are the following:
,hl ,hc I don't think any checking actually happens. Im used to having syntastic checking my files at each save but with Vim-now the only thing that happens is that the left side gets a bit indented in the vim window but no errors.

Also when I'm using ,ht or ,hT I'm getting error saying that type can not be identified or determined. Can you please in the readme give some sample use cases of the examples if I might be using them wrong? 

Also is there a easy way to see see the type of the function under the cursor. The only way I understand now is by using hoogle but I would like to know the type of my own functions.

**Comment by begriffs** [comment]
That is definitely misbehaving, `,ht` should show you the type under the cursor. Are you working with a project inside a cabal sandbox? Is the project able to build and run? I've noticed `ghc-mod` sometimes fails when any imported modules fail to compile.

I'd first verify that running `cabal build` in your project directory is successful. Also what version of GHC and cabal are you using?

**Comment by favetelinguis** [comment]
That did the trick with ,ht, som I'm required to use a cabal sandbox for everything to work properly?

However I'm still having to luck with ,hl ,hc or running syntactic when i write buffer.

**Comment by begriffs** [comment]
I'd advise using sandboxes in general, whether or not you're using ghc-mod. It avoids projects spoiling each others' cabal dependencies.

Also haskell-vim-now does not lint or check on buffer save. It waits for you to check manually. Sometimes the checks can be slow and I didn't want to enable it by default. You could modify `.vimrc.local` though and enable the auto checking. The relevant commands are here: https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L585-L593

To debug the ,hc problem, try running this in the command line

```bash
ghc-mod check /path/to/file.hs
```

See if ghc-mod outputs any errors.

**Comment by favetelinguis** [comment]
Now its working, nut sure what was wrong, did a reboot and it fixed the problem...

Only downside of relying on sandboxes is that NixOS support won't rly work? Im thinking about moving my development to NixOS...

**Comment by begriffs** [comment]
Actually ghc-mod should work OK without a sandbox. I'm not sure what was broken before, I just wanted to verify it would work if your system was configured to be similar to mine (i.e. using a sandbox). Now that we know `,hh` can work on your computer we might try removing the sandbox, building, and trying `,hh` again. I'd like to be sure it can work in the Nix scenario you describe.

**Comment by begriffs** [comment]
@favetelinguis if you're still interested try running the haskell vim now installer again. It will reinstall ghc-mod with some new settings which may work better for you.
