### ISSUE TITLE
Deactivate special signs for haskell applicative etc?

### ISSUE THREAD

**Issue by favetelinguis** [begriffs/haskell-vim-now#60]
Wich setting is it that enables the translation of haskell commands such as <*> etc and how can i deactivate this?

**Comment by begriffs** [comment]
If you want to disable all concealing and use normal Haskell symbols, set

```viml
let g:no_haskell_conceal = 1
```

in your `~/.vimrc.local` file. You can also selectively enable/disable individual symbol substitutions by setting the `g:hscoptions` variable as described [here](https://github.com/enomsg/vim-haskellConcealPlus#available-options)

**Comment by begriffs** [comment]
@favetelinguis did this do what you needed?

**Comment by SimpleX91** [comment]
Well, a lot of time has passed. Consider closing it.

**Comment by favetelinguis** [comment]
Sorry for the very late reply. Yes that fixed the problem, thanks!
