### ISSUE TITLE
GhcModCheck error

### ISSUE THREAD

**Issue by lobachevzky** [begriffs/haskell-vim-now#67]
```
function ghcmod#command#make..ghcmod#make..<SNR>203_system..<SNR>203_plineopen3, line 1
Vim(lcd):E344: Can't find directory "/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/settings:
 openFile: does not exist (No such file or directory)" in cdpath 
Error detected while processing function ghcmod#command#make:
line    7:
E714: List required 
ghc-mod check: No errors found 
```
I get this error when I run `:GhcModCheck` on a Haskell file. In general, ghc-mod does not perform syntax-checking on my files. 

Part of the issue is that I have this directory: "/usr/local/Cellar/ghc/7.10.2/lib/ghc-7.10.2" 
but not this directory: "/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/"

**Comment by begriffs** [comment]
Had you installed haskell-vim-now earlier on when you had GHC 7.8.4, and then deleted 7.8.4 to install 7.10.2? If so maybe ghc-mod is sensitive to library paths that were present at compile time.

Try deleting `~/.haskell-vim-now/bin/ghc-mod*` and running the haskell-vim-now installer again. It will rebuild ghc-mod and hopefully work with your new library path.

**Comment by Lobachevzky** [comment]
Thanks for the response. This eliminated the error I posted, but now `:GhcModCheck` never detects errors and I never get any Syntax correction.

**Comment by begriffs** [comment]
Hmm, maybe the project you're checking needs to be rebuilt with the new ghc as well. Might be a problem of ghc-mod being confused by older binaries.

Also I've noticed ghc-mod have problems when the project you're trying to check has a `dist/` folder. Not sure if it was just a problem with my own machine. Try removing that folder if it exists (just for testing).

**Comment by Lobachevzky** [comment]
You were correct that there was an old `dist/` directory in there and I deleted it. Unfortunately I still have the same problem where :GhcModCheck doesn't catch any errors. Do I need to recompile with GHC?

**Comment by begriffs** [comment]
Yeah try a rebuild.

**Comment by begriffs** [comment]
@Lobachevzky try running the haskell vim now installer again, I just changed it this morning. It will reinstall ghc-mod along with a program called cabal-helper-wrapper which helps ghc-mod build versions of cabal as needed.

**Comment by Lobachevzky** [comment]
Just ran it, but same issue. Tried recompiling in GHC and no change. I do appreciate your help though. Let me know what other info I can give you that might help.

**Comment by begriffs** [comment]
I think this issue is fixed now. Try running the installer again. I've switched to using hdevtools for syntax checking and keep ghc-mod only for type inspection. Should be totally compatible with Stack now.

**Comment by purefn** [comment]
> switched to using hdevtools for syntax checking and keep ghc-mod only for type inspection

Unless I'm missing something, it looks like ghc-mod is no longer used at all since #82 was merged. This isn't a big deal to me - I rather like how fast hdevtools is - except that we've lost ,hT which was quite handy.

**Comment by begriffs** [comment]
That was the case, but as of a few minutes ago I added ghc-mod back again just for the types.

**Comment by SimpleX91** [comment]
But ghc-mod is compatible with stack. It works perfectly fine for me...

**Comment by begriffs** [comment]
@SimpleX91 true, ghc-mod and stack work fine together. It's just that ghc-mod and syntastic are no longer compatible. So I send the syntax checking to hdevtools and keep ghc-mod for type inspection.

**Comment by begriffs** [comment]
I think this issue is no longer relevant so I'm closing it.

**Comment by lobachevzky** [comment]
Sounds good. Thanks.
