### ISSUE TITLE
Haskell-vim-now and stack don't seem to play together nicely yet

### ISSUE THREAD

**Issue by samvher** [begriffs/haskell-vim-now#72]
Hi!

First of all, I really like haskell-vim-now, it's super easy to install and makes my vim environment beautiful.

I used it successfully for quite a while, but recently I started using stack instead of cabal-install (which is also an awesome improvement), and unfortunately I feel like now many things don't work very well anymore. One thing happening in my AWS EC2 environment is that every time  I save I get this syntastic error:

    ghc-mod: Could not find $libexecdir/cabal-helper-wrapper                        
    If you are a developer set the environment variable                             
    `cabal_helper_libexecdir' to override $libexecdir[1]. The following will        
    work in the cabal-helper source tree:                                           
        $ export cabal_helper_libexecdir=$PWD/dist/build/cabal-helper-wrapper       
    [1]: /tmp/build-IARM/.cabal-sandbox/libexec                                     
    If you don't know what I'm talking about something went wrong with your         
    installation. Please report this problem here:                                  
        https://github.com/DanielG/cabal-helper/issues

In another environment ",hc" doesn't seem to work well anymore. This could have something to do with the fact that I have both a local ghc installation and a global one (one in my home dir, the other across users), or that I have my packages installed locally.

(As an aside, auto-indenting doesn't seem to work very well in .lhs files but I'm fairly sure that's a plugin-specific thing, not a haskell-vim-now issue.)

In case all these issues are already fixed, what's the easiest way for me to update haskell-vim-now? (I can git pull, maybe that's all I need to do?)

Oh by the way, I did find this command in a post by Michael Snoyman (https://groups.google.com/forum/#!topic/haskell-stack/8HJ6DHAinU0):

    cabal configure --package-db=clear --package-db=global --package-db=$(stack path --snapshot-pkg-db) --package-db=$(stack path --local-pkg-db)

this solved at least part of my problems, maybe it will be useful for other people as well.

Cheers and thanks!
Sam

**Comment by begriffs** [comment]
Thanks for the bug report. When was the last time you ran the installer? The problem with missing `cabal-helper-wrapper` really messes ghc-mod up under certain cabal versions. I recently added a fix for that:
https://github.com/begriffs/haskell-vim-now/blob/master/install.sh#L88-L92

If you run the installer again it will try to fix the problem. Let's try to get this part fixed on your machine and then look into getting things to work with the stack specific package db location.

**Comment by samvher** [comment]
The re-install solved the cabal-helper-wrapper issue, thanks. ",hc" and ",hl" are still non-functional.

Best

**Comment by SimpleX91** [comment]
I just replaced cabal-install with stack.
stack setup, install all of required utilities (like ghc-mod, hlint etc), export stack's PATH and .local/bin, then removed haskell-vim-now's bin PATH in vimrc. All features work well, no problems so far.

I'm new to haskell world, so maybe (and i bet there is) some better way. Like to make stack and cabal-install co-exist.
P.S. to make ghc-mod work with stack instead of cabal, you should cabal clean in your project dir.

**Comment by xenog** [comment]
Ideally, you do not want `cabal-install`, it is better to stop using it altogether and move completely to `stack` instead of having both. They can coexist nonetheless, but I don’t see why someone would like to continue using `cabal-install`.

**Comment by samvher** [comment]
@SimpleX91: I did what you suggested. Hlint works, and if I run `hoogle data` first I can use the hoogle commands as well. ",hc" (I'm not sure which extension that calls to be honest) does not work, and neither do ",ht"/",hT" (gives a ghcmod: cannot guess type error).

I think the problem is with the libraries installed locally by stack. Many of my imports are not installed globally and I guess that causes trouble. Actually, I did not think of testing this before, but if I edit a simpler program (with no local installs) ",hc" does work as expected. Checking for expression types still causes errors.

**Comment by SimpleX91** [comment]
@samvher you sure you run `cabal clean` in project directory **and** removed PATH export in .vimrc?
I assume you did that, so here're all (I hope) steps, necessary to switch from cabal-install to stack. These steps **do not require** to edit ~/.vimrc.
* install stack
* remove ~/.haskell-vim-now/bin directory (further we'll make a symlink to ~/.local/bin, where stack copies global binaries)
 `rm -r ~/.haskell-vim-now/bin`
* `cd ~/`
* `stack setup` (if you need that)
* `vim ~/.stack/global/stack.yaml` and add cabal-helper to extra-deps (`extra-deps: [cabal-helper-0.6.0.0]`)
* `stack install aeson-pretty codex cpphs ghc-mod hasktags hlint hoogle hscolour hscope pointfree pointful shake stylish-haskell`
* `ln -s ~/.local/bin ~/.haskell-vim-now/bin`
* use stack only: create new projects with `stack new simple` or use existent with `stack init`
* you should get rid of cabal-install sandboxes and other dirs for all your old projects (`cabal sandbox delete`, `cabal clean`)

Well, you should probably add stack's ghc to your PATH (only if something doesn't work):
* add `export PATH=$(stack --verbosity 0 path --bin-path)` to your **~/.bashrc**

Hope that's all and this helps. Good luck!

**Comment by samvher** [comment]
@SimpleX91: I followed your detailed instructions, and it seems everything is working, thanks! I need an additional extra-deps: `- pure-cdb-0.1.1` though. Even with local libraries installed it *seems* to work so far (fingers crossed).

**Comment by begriffs** [comment]
I now have the installer add pure-cdb to the extra-deps. Glad it all works for you now!

You may want to run the installer once more because it now uses hdevtools for compile checking (`,hc`) since ghc-mod and Syntastic no longer work correctly together.
