### ISSUE TITLE
More issues installing from docker

### ISSUE THREAD

**Issue by mitochon** [begriffs/haskell-vim-now#78]
Still having problems (follow up to #69)
````
Step 2 : ADD https://raw.githubusercontent.com/begriffs/haskell-vim-now/master/install.sh /install.sh
Downloading 3.309 kB

 ---> 5fa7f448c073
Removing intermediate container 0c9f057c93a7
Step 3 : RUN /bin/bash /install.sh && rm -r /root/.cabal
 ---> Running in b1b3d6a5b5b5
--- Installer requires Stack. Installation instructions:
--- https://github.com/commercialhaskell/stack#how-to-install
````

I have stack installed in my machine.
````
{9:47}~/Downloads/haskell-vim-now:master ✓ ➭ which stack
/Users/mitochon/Applications/ghc-7.10.2.app/Contents/bin/stack
{9:47}~/Downloads/haskell-vim-now:master ✓ ➭ command -v stack >/dev/null && echo $?
0
````

Does stack need to be part of the Dockerfile?

**Comment by begriffs** [comment]
Ah yes, I just switched the project over to using Stack. In fact at this moment I was testing that it works in various Linux distros. We will need to update the Dockerfile to install stack. Would you like to help out and send a pull request?

**Comment by mitochon** [comment]
Using the above changes was able to complete the setup.

However there's also another issue with the last command but is not a hard failure so will leave it alone for now. Looked around a little bit couldn't find the .cabal directory in the resulting docker container.

```
--- Setting git to use fully-pathed vim for messages...
--- Configuring codex to search in stack...
rm: cannot remove ‘/root/.cabal’: No such file or directory
The command '/bin/sh -c /bin/bash /install.sh && rm -r /root/.cabal' returned a non-zero code: 1
````
