### ISSUE TITLE
Using vim-plug instead of Vundle

### ISSUE THREAD

**Issue by Tehnix** [begriffs/haskell-vim-now#81]
I was wondering if there was any specific reason for using _Vundle_ instead of [vim-plug](https://github.com/junegunn/vim-plug), for package management?

While loading everything immediately may be fine for the people that are literally only using this VIM for haskell, _vim-plug_ enables lazy-loading and is generally faster than _Vundle_ in my experience.

For example, you can even do stuff like,

```
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
``` 

to only load the _nerdtree_ package when actually using it. Honestly, _vim-plug_ supports a lot more things like post-update hooks, specifying specific versions of packages and much more, while still being super fast.

For almost anything it should be super easy to switch to _vim-plug_. If people are interested in this, I don't mind making a fork, testing it, and submitting a pull request :)

**Comment by begriffs** [comment]
Sounds cool! I'd take a PR for sure if you care to put it together. The installer will need to be adjusted too https://github.com/begriffs/haskell-vim-now/blob/master/install.sh#L89

**Comment by Tehnix** [comment]
Cool! I'll take a stab at it then :)

**Comment by begriffs** [comment]
Thanks!

**Comment by SimpleX91** [comment]
Check out my pull request =)

**Comment by Tehnix** [comment]
@SimpleX91 awesome work! :) I'll close it since I can.
