### ISSUE TITLE
How to Update/Remove?

### ISSUE THREAD

**Issue by aozgaa** [begriffs/haskell-vim-now#82]
How can I update my installation to the latest version? Is it done automagically on startup?

Should I remove/reinstall the plugins?

Similarly, is it possible to remove haskell-vim-now without leaving artifacts on my system? How would one go about doing that, if possible?

Perhaps I'm missing something, but I can't seem to find any documentation on the matter. I'd be happy to update the readme with this info. Thanks for the help!

**Comment by begriffs** [comment]
You can run the install script again to update.

You can find your original config file saved in `~/.vimrc.yearmonthdate_time`. To go back to it remove the `.vimrc` (file which is a symlink) and rename the backup file.

**Comment by begriffs** [comment]
@aozgaa did this answer your question?

**Comment by carldong** [comment]
Updating destroyed my vimrc.local and .vim.local, and I have to config everything again

**Comment by carldong** [comment]
Nevermind, I found it under .config/haskell-vim-now/vimrc.local

**Comment by begriffs** [comment]
Yeah the directory structure has changed and things now live in `.config` to better match a unix convention. Could we improve the docs in some way to avoid the scare of feeling like your config is deleted?

**Comment by SimpleX91** [comment]
Well, I did change readme to match latest changes. Maybe update FAQ section in wiki? Or add more info in install.sh about migration?

**Comment by begriffs** [comment]
Now that the readme is updated I'm closing this issue. Feel free to reopen if there is still confusion.
