### ISSUE TITLE
Unable to install on vim version 7.4.

### ISSUE THREAD

**Issue by wpoosanguansit** [begriffs/haskell-vim-now#83]
I do have vim 7.4 on Mac OS x 10.9:

vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  2 2015 15:19:40)
MacOS X (unix) version
Included patches: 1-712
Compiled by Homebrew

But I still do get

--- Vim version 7.4 or later is required. Aborting.

I am not sure how to configure it to set the flag to true.  Thanks for your help.

**Comment by begriffs** [comment]
Try running the install script again and let me know what it says. I updated it to provide more debugging info when the version check fails.

**Comment by wpoosanguansit** [comment]
Thanks for your help.  I see something odd with the version.

--- Detected vim version "7.3"
--- However version 7.4 or later is required. Aborting.

But when I do vim --version:

> vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  2 2015 15:19:40)

I do see in the install script to be checking vim --version.  So I am not quite sure how things diverge.  I am using brew and I do set the override system flag on as well.  Any suggestion?

**Comment by wpoosanguansit** [comment]
I think I have figured it out.  Turns out that I am using zsh shell and the command was bash which is still pointing to vim 7.3.  I am closing this.  Thanks for your help.
