### ISSUE TITLE
In mvim "syntastic: warning: checker ghc_mod is not available"

### ISSUE THREAD

**Issue by jacksonja** [begriffs/haskell-vim-now#84]
While using ghc-mod to check a file from within mvim, but not shell based vim, I get the "syntastic: warning: checker ghc_mod is not available" error. This is based off of a fresh install as of November 4, 2015.

**Comment by begriffs** [comment]
Syntastic is in a weird place right now with ghc-mod. https://github.com/scrooloose/syntastic/issues/1576

It's pretty sad, all the rest of the ghc-mod functionality works with vim but not the error checking. I would downgrade ghc-mod to work with syntastic but then it would not work with Stack, so we're stuck.

**Comment by jacksonja** [comment]
Note that the ghc-mod checking works fine from vim within a shell, just not from the gui version.

**Comment by begriffs** [comment]
Wait so within vim from the shell you can type `,gc` and it will detect errors in your haskell code? But in macvim it does not?

**Comment by jacksonja** [comment]
I looked more closely and it appears it doesn't work. the error message just disappears faster in regular vim so I didn't notice it before.

**Comment by Saulzar** [comment]
I get the same error. I tried enabling the syntastic debugging now all I get whenever I hit  ``` ,h  ``` is "E20: Mark not set"

On my work computer I just get "E20: Mark not set" from the outset.

**Comment by begriffs** [comment]
I pushed a change to use hdevtools rather than ghc-mod. Works great on my machine now! Run the installer again to upgrade. Let me know if it fixes things for you and we can close this issue.

**Comment by jacksonja** [comment]
,hc checks fine now. However, hdevtools type lookups are not as good. For example, if you do an ,ht on the definition of a function, it only shows the result type of the function and not the whole parameter/result type. It also doesn't appear to allow you to generate the type. Is it possible to use hdevtools just for the ,hc, but still use ghc-mod for ,ht and ,hT?

**Comment by begriffs** [comment]
@jacksonja great idea. Run the installer again and see how you like it.

**Comment by jacksonja** [comment]
That works well.

Thank you,
Jason
