### ISSUE TITLE
`,hc` fails (almost) silently

### ISSUE THREAD

**Issue by skatenerd** [begriffs/haskell-vim-now#85]
I am running `GHC 7.10.2` (on ubuntu) and I'm using `Stack` and resolver `lts-3.11`.  I followed the advice I found in various issues, and I ran `cabal configure --package-db="$(stack ......)"`.

I am in a situation where `,ht` and `,hl` work perfectly, but `,hc` fails silently.

The _first time_ I invoke `,hc`, a red error message flashes at the bottom of the screen.  This message flashes too quickly for me to read it, so I'm a little bit lost as to how to diagnose the problem.

FWIW, `ghc-mod check src/Main.hs` runs successfully and gives me warnings about (e.g.) unused bindings.

Thanks for your help :-)

**Comment by skatenerd** [comment]
Hmm, if I look at the runtime logs for Vim, I see:
`syntastic: warning: checker ghc_mod is not available`

This is bizarre, seeing as line 40 of my `.vimrc` is putting `~/.local/bin` in the `PATH`...

**Comment by begriffs** [comment]
This is an annoying issue with Syntastic. See #84.

**Comment by skatenerd** [comment]
Hm.  Looks like this isn't going to be working in the near future.  If I want typecheck-on-save, I'll probably have to start using `hdevtools-vim`..?

Do you have any pitfalls / advice for moving to `hdevtools-vim`?  Will it play nicely with the rest of the `haskell-vim-now` setup?

**Comment by skatenerd** [comment]
(Thanks for getting back to me @begriffs )

**Comment by begriffs** [comment]
It should play just fine with the rest. I'm working on switching over my local config right now. I'll open a PR as soon as I get something. Maybe you could experiment at the same time on your machine.

**Comment by skatenerd** [comment]
When I try to run `:HdevtoolsType`, Vim tells me `The client sent an invalid message to the server: "SrvCommand (CmdType \"/home/skatenerd/development/vectorracing/src/Main.hs\" (83,17)) (CommandExtra {ceGhcOptions = [], ceCabalConfig = Just \"/home/skate
nerd/development/vectorracing/./vectorracing.cabal\", cePath = Just \"src/Main.

It looks like the server is failing to even recognize the command...

**Comment by begriffs** [comment]
Actually I've got it working locally! I had to change a few things in various places. Let me prepare a pull request.

**Comment by skatenerd** [comment]
Yussssssssssss

**Comment by begriffs** [comment]
OK, it's merged. Try running the install script again:

```bash
bash <(curl -sL http://git.io/haskell-vim-now)
```

**Comment by skatenerd** [comment]
Still getting: `The client sent an invalid message to the server: "SrvCommand (CmdType \"/home/skatenerd/development/vectorracing/src/Main.hs\" (97,11)) (CommandExtra {ceGhcOptions = [], ceCabalConfig = Just \"/home/skate
nerd/development/vectorracing/./vectorracing.cabal\", cePath = Just \"src/Main.hs\"})"`

Any ideas?

**Comment by begriffs** [comment]
Ah OK. Note that you should have an installation of hdevtools in `~/.local/bin` which the haskell vim now installer put there. That's the one to use.

**Comment by begriffs** [comment]
@skatenerd hey try the installer again. I have it use both ghc-mod and hdevtools now. Mod for type inspection and devtools for syntax checking. Best of both worlds.

**Comment by skatenerd** [comment]
Awesome, thanks.

I'm still working out some of the kinks on my machine...
