### ISSUE TITLE
NeoVim support

### ISSUE THREAD

**Issue by SimpleX91** [begriffs/haskell-vim-now#87]
How about supporting NeoVim? I'm using it now with haskell-vim-now and most of the time it works fine. It has some problems with NERDTree.

NeoVim provides async features, which could enhance user experience with, for example, automatic async checks with ghc-mod on save.

[Here](https://neovim.io/doc/user/nvim_from_vim.html) described how to easily symlink vim config to nvim's.

**Comment by begriffs** [comment]
Sure let's see what we can do. Please create a specific github issue for the problem you're having with nerdtree.

**Comment by SimpleX91** [comment]
As soon as I face it again, sure.
Anyway, it's easy to provide nvim support just by symlinking vim config to nvim's. So it could be useful to add checks for nvim in PATH and if it's there - make symlinks.

**Comment by SimpleX91** [comment]
If I try to open NERDTree in quickfix, it throws this errors:
```
Error detected while processing function ToggleFindNerd..<SNR>60_findAndRevealPath:                                     
line   27:                                                                                                              
E121: Undefined variable: path                                                                                          
E116: Invalid arguments for function 122                                                                                
E15: Invalid expression: !p.isUnder(g:NERDTreeFileNode.GetRootForTab().path)                                            
Error detected while processing function ToggleFindNerd..<SNR>60_findAndRevealPath..301..309:                           
line    2:                                                                                                              
E605: Exception not caught: NERDTree.TreeNotOpen                                                                        
Error detected while processing function ToggleFindNerd:                                                                
line    4:                                                                                                              
E171: Missing :endif
```
No such problem in Vim, only NeoVim. Other than that it works just fine.

**Comment by Tehnix** [comment]
It would be cool with NeoVim support, but there are some considerations that need to be taken in the .vimrc file, since neovim now puts everything in .config/neovim and uses init.vim instead of a .vimrc file.

One immediate thing that I spotted was [line 276](https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L276) which sources the vim file on save.

I'll try and look into setting it up on my machine and see if I can spot any immediate things :)

**Comment by SimpleX91** [comment]
Not a problem. I use HVN with neovim 0.1.1 without issues at all. Just make symlinks to .vim and .vimrc to .config/neovim and .config/neovim/init.vim. Thats really all you need to do!

**Comment by Tehnix** [comment]
I'm currently working on a pull-request for this - I was wondering how you normally go around about testing this? Mostly I'm concerned about if I did the symlinking process correctly.

For the curious, I'm adding a couple of things to the .vimrc that are neovim specific, like its terminal emulation, a problem with <c-h> along with not setting the encoding for neovim.
