### ISSUE TITLE
Comma first indentation?

### ISSUE THREAD

**Issue by carldong** [begriffs/haskell-vim-now#93]
I found the indentation quite problematic. One of which is comma first auto indentation (the other is documentation, but that is another problem)

```
data A = {
    a :: a
  , b :: b
}
```

Currently I don't see any way to make the first line align at the correct position. I only tried `==` command, but all the alignment provided in this bundle will mess the entire thing.

BTW, `haskell-mode` in Emacs works perfectly on this aspect, though

**Comment by begriffs** [comment]
As an experiment I tried installing `hindent` and updating https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L50 to

```viml
autocmd FileType haskell let &formatprg="hindent --style johan-tibell -XQuasiQuotes"
```

Then I can use vim's `gq` action to format the paragraph which yields

```haskell
data A = A
    { a :: a
    , b :: b
    } 
```

It chooses more spaces for indentation than I would like but is maybe closer to what you want. What do you think?

**Comment by carldong** [comment]
It is something like that

**Comment by begriffs** [comment]
Would you like me to merge this change into master? It will not improve auto indentation but it will allow you to apply `gq` to a selection or movement to fix it up.

**Comment by carldong** [comment]
Yes please. Thank you!
