### ISSUE TITLE
Installing in cygwin

### ISSUE THREAD

**Issue by ideruga** [begriffs/haskell-vim-now#98]
Tried installing it with cygwin (64 bit). I've found all the packages needed, but then I had this error with 7zip. Is it more of a stack problem?

	Preparing to download 7z.exe ...
	Already downloaded.
	C:\Users\d00ide\AppData\Local\Programs\stack\x86_64-windows\7z.exe: rawSystem: invalid argument (Invalid argument)
	--- Adding extra stack deps if needed
	sed: impossible de lire /home/d00ide/.stack/global-project/stack.yaml: No such file or directory
	sed: impossible de lire /home/d00ide/.stack/global/stack.yaml: No such file or directory
	sed: impossible de lire /home/d00ide/.stack/global-project/stack.yaml: No such file or directory
	sed: impossible de lire /home/d00ide/.stack/global/stack.yam: No such file or directory
	--- Installing helper binaries
	Run from outside a project, using implicit global project config
	Selected resolver: nightly-2015-11-17
	Downloading nightly-2015-11-17 build plan ...
	Downloaded nightly-2015-11-17 build plan.
	Caching build plan
	No compiler found, expected minor version match with ghc-7.10.2 (x86_64) (based on resolver setting in C:\Users\d00ide\AppData\Roaming\stack\global-project\stack.yaml).
	Try running "stack setup" to install the correct GHC into C:\Users\d00ide\AppData\Local\Programs\stack\x86_64-windows\
	--- Installing git-hscope
	cp: impossible de créer le fichier standard « /home/d00ide/.local/bin »: No such file or directory
	--- Building Hoogle database...
	/dev/fd/63: ligne 113: /home/d00ide/.local/bin/hoogle: No such file or directory
	--- Setting git to use fully-pathed vim for messages...
	--- Configuring codex to search in stack...

**Comment by SimpleX91** [comment]
Please, run:
```stack --verbosity 0 path --global-stack-root```
```stack --verbosity 0 path --local-bin-path```
and post the results.

**Comment by SimpleX91** [comment]
@begriffs we can use stack-bin path provided by stack in .vimrc ```let stack_path = system("stack --verbosity 0 path --local-bin-path")``` and replace all "~/.local/bin" with stack_path variable.
I already use it in install.sh in move-to-xdg branch, so I can just add it there.

Well, I don't like it being executed on every vim startup, but don't know a better way.

**Comment by ideruga** [comment]
So, I re-run the script in cygwin (another computer), and I get the following now:
- First, there are some wornings
> --- Adding extra stack deps if needed
> sed: impossible de lire /home/Utilisateur/.stack/global-project/stack.yaml: No such file or directory
> sed: impossible de lire /home/Utilisateur/.stack/global/stack.yaml: No such file or directory
> sed: impossible de lire /home/Utilisateur/.stack/global-project/stack.yaml: No such file or directory
> sed: impossible de lire /home/Utilisateur/.stack/global/stack.yaml: No such file or directory
- Then, I got this error:
> While constructing the BuildPlan the following exceptions were encountered:
> --  Failure when adding dependencies:
>       pure-cdb: needed (-any), not present in build plan (latest is 0.1.1)
>     needed for package: hscope-0.4.2
> --  While attempting to add dependency,
>     Could not find package pure-cdb in known packages
> 
> Recommended action: try adding the following to your extra-deps in C:\Users\Utilisateur\AppData\Roaming\stack\global-project\stack.yaml
> - pure-cdb-0.1.1

If I need to set the path manually to make it run in cygwin, I think that this needs to be added on the main page... Also, cygwin needs libcurl-devel to run this (dependency on curl-config).

**Comment by ideruga** [comment]
@SimpleX91 I did what you asked:
$ stack --verbosity 0 path --global-stack-root
C:\Users\Utilisateur\AppData\Roaming\stack

$ stack --verbosity 0 path --local-bin-path
C:\Users\Utilisateur\AppData\Roaming\local\bin

**Comment by ideruga** [comment]
I've found this in the code: 

> sed -i.bak "$DEPS_REGEX" ~/.stack/global-project/stack.yaml || sed -i.bak "$DEPS_REGEX" ~/.stack/global/stack.yaml

but I don't even have ~/.stack directory. In my case, it can be found at:

>  /cygdrive/c/Users/Utilisateur/AppData/Roaming/stack/global-project/stack.yaml

**Comment by SimpleX91** [comment]
Try my move-to-xdg branch. It should work. At least for installation.

**Comment by begriffs** [comment]
The changes are now merged to master so you can try running the installer again.

**Comment by SimpleX91** [comment]
@begriffs vimrc still use hard-coded path, so vim won't work as should. Need to do something.

**Comment by ideruga** [comment]
@begriffs I tried to create a fork and do exactly as you did, but the problem is that my $STACK_GLOBAL folder is windows-style: "C:\blahblah" and in order to make sed work, I need "/cygwin/c/blahblah"... I will try it however, and will keep you posted...

**Comment by ideruga** [comment]
@begriffs Ok, so I got my paths wrong, your version worked fine!

**Comment by ideruga** [comment]
@SimpleX91 I just tried and I have no problem with .vimrc: no errors while editing a random file. Can you point me to the problem? Which paths are hard-coded?

**Comment by ideruga** [comment]
Ok, guys, so I'm pretty slow, sorry for that. Tried editing a .hs file and got this:

> "Lib.hs" 6L, 88C
> hdevtools: hdevtools is not executable!
> [vimproc] vimproc's DLL: "/home/Utilisateur/.config/haskell-vim-now/.vim/bundle/vimproc.vim/lib/vimproc_cygwin.dll" is not found.  Please read :help vimproc and
>  make it.
> [vimproc] vimproc's DLL: "/home/Utilisateur/.config/haskell-vim-now/.vim/bundle/vimproc.vim/lib/vimproc_cygwin.dll" is not found.  Please read :help vimproc and
>  make it.
> ghcmod: vimproc.vim is not installed!

**Comment by SimpleX91** [comment]
@ideruga https://github.com/begriffs/haskell-vim-now/blob/master/.vimrc#L53 is the reason of hdevtools error.
We need to use actual stack path instead of hard-coded one. Either we should add special (autogenerated on install) HVM configuration file OR run `stack path` on every Vim launch (which is overkill, stack won't magically change it's path).

**Comment by ideruga** [comment]
Would it be considered a hack if you did the replacement in this line:
> detail "~/.vimrc -> $DESTINATION/.vimrc"
using `stack path`?

**Comment by ideruga** [comment]
So, I tried this: 
> https://github.com/ideruga/haskell-vim-now/blob/master/install.sh#L151

but still no luck. Finally, when I checked, I still get the errors: 

> sed: impossible de lire C:\Users\Utilisateur\AppData\Roaming\stack^M/global-project/stack.yaml: No such file or directory
sed: impossible de lire C:\Users\Utilisateur\AppData\Roaming\stack^M/global/stack.yaml: No such file or directory
sed: impossible de lire C:\Users\Utilisateur\AppData\Roaming\stack^M/global-project/stack.yaml: No such file or directory
sed: impossible de lire C:\Users\Utilisateur\AppData\Roaming\stack^M/global/stack.yaml: No such file or directory

**Comment by ideruga** [comment]
Ok, so this seems to have helped: https://github.com/ideruga/haskell-vim-now/blob/master/install.sh#L106
If you want me to make a pull-request, I could, but I'd have to make a clean up first. And I can't test my changes on linux...

Now, the .hs file opens without warnings, but I still have some nuances during installation. I am attaching the full error log (2>errors).
[errors.txt](https://github.com/begriffs/haskell-vim-now/files/45308/errors.txt)

**Comment by begriffs** [comment]
Glad you're making progress. I'd say clean up your changes and send a pull request. I can test your changes on Mac and Linux.

**Comment by SimpleX91** [comment]
Need something like "fix_path" function, which would return correct path for cygwin (and argument for others).

**Comment by begriffs** [comment]
Looks like cygwin provides a [cygpath](https://www.cygwin.com/cygwin-ug-net/cygpath.html) helper program for that.

**Comment by SimpleX91** [comment]
@begriffs still need someone on cygwin to test it.

Does OSX have any special directory for config files?

**Comment by begriffs** [comment]
I downloaded a Windows 10 image for VirtualBox and have cywgin on it now so I can test if you put together a branch.

**Comment by ideruga** [comment]
Hi guys,
So I tried running the master branch in cygwin, attached the log file.

As for my branch, it's obvious that I'm not capable of delivering at your speed. So, I could try to test your solutions with some delay (a couple of days or so).
[haskell_vim_now_2015-11-30.txt](https://github.com/begriffs/haskell-vim-now/files/47298/haskell_vim_now_2015-11-30.txt)
