### ISSUE TITLE
Move haskell-vim-now to $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by SimpleX91** [begriffs/haskell-vim-now#99]
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
A lot of apps already honour this spec. Moving haskell-vim-now configs to .config directory would be nice and make $HOME cleaner of dot-files.

I've made initial changes to easily move to .config with user configs migrations (not ready for a PR yet):
https://github.com/SimpleX91/haskell-vim-now/commit/5689465cebeeaf801233103536bbd3d740aee7cc
https://github.com/SimpleX91/haskell-vim-now/commit/84b0fc4439cbd4303e5b87dce6bb6ab5cb9b6a79
https://github.com/SimpleX91/haskell-vim-now/commit/8f97d6aefd13dc83c0970b60cfb47de78f9a0692
https://github.com/SimpleX91/haskell-vim-now/commit/f2f95c39bc5aec0f320c13e2a35a9d6b069a124a
https://github.com/SimpleX91/haskell-vim-now/commit/74b2af0e5f28838abc1b49f5aac08e9478bf0af0

If you're interested, I'd gladly make a PR with this changes.

**Comment by begriffs** [comment]
Yes I'd love to use a more standard directory structure. A PR would be great!

**Comment by SimpleX91** [comment]
Then could you please test vim-plug PR once more? My changes are based on it..

There would be following changes:
* ~/.config/haskell-vim-now/ is the new project directory (DIR)
* .vimrc and .vim backups moved to DIR/backup/...
* user configs placed to DIR/vimrc.local DIR/plugins.local
* automated migration of user configs and installation (not sure i've done everything needed)
* installer now use stack to find it's configuration and bin path

**Comment by SimpleX91** [comment]
https://github.com/SimpleX91/haskell-vim-now/commits/move-to-xdg
Done.
